#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_103912_BP

#include "Basic.hpp"

#include "PyAbility_103912_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103912_BP.Ability_103912_BP_C
// 0x0000 (0x2A08 - 0x2A08)
class UAbility_103912_BP_C final : public UPyAbility_103912
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103912_BP_C">();
	}
	static class UAbility_103912_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103912_BP_C>();
	}
};
static_assert(alignof(UAbility_103912_BP_C) == 0x000008, "Wrong alignment on UAbility_103912_BP_C");
static_assert(sizeof(UAbility_103912_BP_C) == 0x002A08, "Wrong size on UAbility_103912_BP_C");

}

