#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_104492_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyAbility_104492_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104492_BP.Ability_104492_BP_C
// 0x0008 (0x29F8 - 0x29F0)
class UAbility_104492_BP_C final : public UPyAbility_104492
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x29F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AE_OnAbilityInitialized();
	void ExecuteUbergraph_Ability_104492_BP(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104492_BP_C">();
	}
	static class UAbility_104492_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104492_BP_C>();
	}
};
static_assert(alignof(UAbility_104492_BP_C) == 0x000008, "Wrong alignment on UAbility_104492_BP_C");
static_assert(sizeof(UAbility_104492_BP_C) == 0x0029F8, "Wrong size on UAbility_104492_BP_C");
static_assert(offsetof(UAbility_104492_BP_C, UberGraphFrame) == 0x0029F0, "Member 'UAbility_104492_BP_C::UberGraphFrame' has a wrong offset!");

}

