#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_102831_BP

#include "Basic.hpp"

#include "PyAbility_102831_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102831_BP.Ability_102831_BP_C
// 0x0000 (0x2A00 - 0x2A00)
class UAbility_102831_BP_C final : public UPyAbility_102831
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102831_BP_C">();
	}
	static class UAbility_102831_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102831_BP_C>();
	}
};
static_assert(alignof(UAbility_102831_BP_C) == 0x000008, "Wrong alignment on UAbility_102831_BP_C");
static_assert(sizeof(UAbility_102831_BP_C) == 0x002A00, "Wrong size on UAbility_102831_BP_C");

}

