#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_PyPlayEmoteBattleChess

#include "Basic.hpp"

#include "PyBTNodeBase_classes.hpp"


namespace SDK
{

// PythonClass BTT_PyPlayEmoteBattleChess.BTT_PyPlayEmoteBattleChess
// 0x0010 (0x00D0 - 0x00C0)
class UBTT_PyPlayEmoteBattleChess : public UBTTask_PyBase
{
public:
	int32                                         DefaultEmoteSkinID;                                // 0x00C0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DefaultEmoteActionID;                              // 0x00C4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EmoteTypeID;                                       // 0x00C8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsSinglePlayEmote;                                 // 0x00CC(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsRandomPlayEmote;                                 // 0x00CD(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BTT_PyPlayEmoteBattleChess">();
	}
	static class UBTT_PyPlayEmoteBattleChess* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_PyPlayEmoteBattleChess>();
	}
};
static_assert(alignof(UBTT_PyPlayEmoteBattleChess) == 0x000008, "Wrong alignment on UBTT_PyPlayEmoteBattleChess");
static_assert(sizeof(UBTT_PyPlayEmoteBattleChess) == 0x0000D0, "Wrong size on UBTT_PyPlayEmoteBattleChess");
static_assert(offsetof(UBTT_PyPlayEmoteBattleChess, DefaultEmoteSkinID) == 0x0000C0, "Member 'UBTT_PyPlayEmoteBattleChess::DefaultEmoteSkinID' has a wrong offset!");
static_assert(offsetof(UBTT_PyPlayEmoteBattleChess, DefaultEmoteActionID) == 0x0000C4, "Member 'UBTT_PyPlayEmoteBattleChess::DefaultEmoteActionID' has a wrong offset!");
static_assert(offsetof(UBTT_PyPlayEmoteBattleChess, EmoteTypeID) == 0x0000C8, "Member 'UBTT_PyPlayEmoteBattleChess::EmoteTypeID' has a wrong offset!");
static_assert(offsetof(UBTT_PyPlayEmoteBattleChess, IsSinglePlayEmote) == 0x0000CC, "Member 'UBTT_PyPlayEmoteBattleChess::IsSinglePlayEmote' has a wrong offset!");
static_assert(offsetof(UBTT_PyPlayEmoteBattleChess, IsRandomPlayEmote) == 0x0000CD, "Member 'UBTT_PyPlayEmoteBattleChess::IsRandomPlayEmote' has a wrong offset!");

}

