#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterOverlayManager

#include "Basic.hpp"

#include "PyCharacterOverlayManager_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CharacterOverlayManager.CharacterOverlayManager_C
// 0x0000 (0x06F0 - 0x06F0)
class ACharacterOverlayManager_C final : public APyCharacterOverlayManager
{
public:
	uint8                                         Pad_6E5[0x3];                                      // 0x06E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CharacterOverlayManager_C">();
	}
	static class ACharacterOverlayManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACharacterOverlayManager_C>();
	}
};
static_assert(alignof(ACharacterOverlayManager_C) == 0x000010, "Wrong alignment on ACharacterOverlayManager_C");
static_assert(sizeof(ACharacterOverlayManager_C) == 0x0006F0, "Wrong size on ACharacterOverlayManager_C");
static_assert(offsetof(ACharacterOverlayManager_C, DefaultSceneRoot) == 0x0006E8, "Member 'ACharacterOverlayManager_C::DefaultSceneRoot' has a wrong offset!");

}

