#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cue_Summoner_Loop_10478501_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cue_Summoner_Loop_10478501_BP.Cue_Summoner_Loop_10478501_BP_C
// 0x0020 (0x1280 - 0x1260)
class ACue_Summoner_Loop_10478501_BP_C final : public AMarvelCueNotify_Summoned
{
public:
	uint8                                         Pad_1258[0x8];                                     // 0x1258(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      NS_104785_Loop_02;                                 // 0x1260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_FlowL;                                          // 0x1268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_FlowR;                                          // 0x1270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 ToySkeletalMesh;                                   // 0x1278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Cue_Summoner_Loop_10478501_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Summoner_Loop_10478501_BP_C")
	}
	static class ACue_Summoner_Loop_10478501_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Summoner_Loop_10478501_BP_C>();
	}
};
DUMPER7_ASSERTS_ACue_Summoner_Loop_10478501_BP_C;

}

