#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GuidePoint104242

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GuidePoint104242.GuidePoint104242_C
// 0x0010 (0x06F0 - 0x06E0)
class AGuidePoint104242_C final : public AActor
{
public:
	uint8                                         Pad_6D8[0x8];                                      // 0x06D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x06E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GuidePoint104242_C">();
	}
	static class AGuidePoint104242_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGuidePoint104242_C>();
	}
};
static_assert(alignof(AGuidePoint104242_C) == 0x000010, "Wrong alignment on AGuidePoint104242_C");
static_assert(sizeof(AGuidePoint104242_C) == 0x0006F0, "Wrong size on AGuidePoint104242_C");
static_assert(offsetof(AGuidePoint104242_C, DefaultSceneRoot) == 0x0006E0, "Member 'AGuidePoint104242_C::DefaultSceneRoot' has a wrong offset!");

}

