#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hero_1049

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "Hero_1049_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Hero_Synergy_classes.hpp"


namespace SDK
{

// Class Hero_1049.AbilityExtraStatistics_104911
// 0x0000 (0x0070 - 0x0070)
class UAbilityExtraStatistics_104911 final : public UAbilityExtraStatistics
{
public:
	void OnApplyPercentDamage(float PercentDamageValue, const struct FGameplayEffectSpec& SourceSpec);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AbilityExtraStatistics_104911")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AbilityExtraStatistics_104911")
	}
	static class UAbilityExtraStatistics_104911* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityExtraStatistics_104911>();
	}
};
DUMPER7_ASSERTS_UAbilityExtraStatistics_104911;

// Class Hero_1049.AbilityExtraStatistics_104921
// 0x0010 (0x0080 - 0x0070)
class UAbilityExtraStatistics_104921 final : public UAbilityExtraStatistics
{
public:
	uint8                                         Pad_70[0x10];                                      // 0x0070(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AbilityExtraStatistics_104921")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AbilityExtraStatistics_104921")
	}
	static class UAbilityExtraStatistics_104921* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbilityExtraStatistics_104921>();
	}
};
DUMPER7_ASSERTS_UAbilityExtraStatistics_104921;

// Class Hero_1049.Config_104901
// 0x0050 (0x00E8 - 0x0098)
class UConfig_104901 : public UMarvelAbilityConfig
{
public:
	float                                         NotTreatShieldDuration;                            // 0x0098(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ExtraBaseHealth;                                   // 0x009C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            AdjustNotTreatShieldFactorCurve;                   // 0x00A0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NotTreatShieldToHealthFactor;                      // 0x00A8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           AngerValueType;                                    // 0x00AC(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           HealUITipTag;                                      // 0x00B8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           HealCDTag;                                         // 0x00C4(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShieldToHealDelay;                                 // 0x00D0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HealToEndDelay;                                    // 0x00D4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBindReduceCDMethod_104901                    ReduceCDMethod_NotActivated;                       // 0x00D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D9[0x3];                                       // 0x00D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ReduceCDValue_NotActivated;                        // 0x00DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBindReduceCDMethod_104901                    ReduceCDMethod_Activated;                          // 0x00E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ReduceCDValue_Activated;                           // 0x00E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_104901")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_104901")
	}
	static class UConfig_104901* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_104901>();
	}
};
DUMPER7_ASSERTS_UConfig_104901;

// Class Hero_1049.Ability_104901
// 0x0088 (0x2AC8 - 0x2A40)
class UAbility_104901 : public UMarvelGameplayAbility
{
public:
	TMulticastInlineDelegate<void(bool bCanHeal)> OnEnterHealStageDispatcher;                        // 0x2A40(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ResurrectCount)> OnResurrectSelfDispatcher;                  // 0x2A50(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A60[0x18];                                    // 0x2A60(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	class UConfig_104901*                         MyConfig;                                          // 0x2A78(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AMarvelBaseCharacter*                   OwnerCharacter;                                    // 0x2A80(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ReduceCDCount_Activated;                           // 0x2A88(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ResurrectCount;                                    // 0x2A8C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ReplicatedResurrectCount;                          // 0x2A90(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2A94[0x4];                                     // 0x2A94(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           DelayHealTimerHandle;                              // 0x2A98(0x0018)(BlueprintVisible, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FTimerHandle                           DelayEndAbilityTimerHandle;                        // 0x2AB0(0x0018)(BlueprintVisible, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void BindNotTreatShieldChanged(bool bBind);
	bool CanResurrectSelf();
	void DelayEndAbility();
	void NotTreatShieldToHeal();
	void OnAbilityActivateFailed(const struct FGameplayTagContainer& FailureReason);
	void OnOwnerApplyDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnOwnerTagUpdate(const struct FGameplayTag& InTag, bool bInExists);
	void OnRep_ReplicatedResurrectCount();
	void OnTargetActorDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void TryResurrectSelf();
	void UpdateOwnerResurrectStatus();

	float AdjustNotTreatShieldByAnger() const;
	float GetAngerToShieldFactor(float InAngerValue) const;
	float GetCurrentAngerValue() const;
	float GetExtraBaeHealthValue() const;
	float GetTreatHealth() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_104901")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_104901")
	}
	static class UAbility_104901* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104901>();
	}
};
DUMPER7_ASSERTS_UAbility_104901;

// Class Hero_1049.MarvelCueNotify_Ability_10490101
// 0x00B0 (0x1270 - 0x11C0)
class AMarvelCueNotify_Ability_10490101 final : public AMarvelCueNotify_Ability
{
public:
	class FName                                   ShieldSwitchName;                                  // 0x11C0(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ShieldDissolveName;                                // 0x11CC(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            DissolveCurve;                                     // 0x11D8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            AppearCurve;                                       // 0x11E0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   RimFresnelPowerName;                               // 0x11E8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11F4[0x4];                                     // 0x11F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            RimFresnelPowerCurve;                              // 0x11F8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   RimFresnelScaleName;                               // 0x1200(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_120C[0x4];                                     // 0x120C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            RimFresnelScaleCurve;                              // 0x1210(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayActivateCameraShakeTime;                      // 0x1218(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_121C[0x4];                                     // 0x121C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           DelayActivateCameraShakeTimerHandle;               // 0x1220(0x0018)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class ULegacyCameraShake>         ShieldActivateCameraShake;                         // 0x1238(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class ULegacyCameraShake>         ShieldDissolveCameraShake;                         // 0x1240(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShouldPlayDissolveCameraShakeWithOutArmor;        // 0x1248(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1249[0x3];                                     // 0x1249(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AccumulateDissolveTime;                            // 0x124C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bShouldPlayDissolveCurve;                          // 0x1250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1251[0x3];                                     // 0x1251(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AccumulateAppearTime;                              // 0x1254(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bShouldPlayAppearCurve;                            // 0x1258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1259[0x7];                                     // 0x1259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelBaseCharacter*                   OwnerCharacter;                                    // 0x1260(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAbility_104901*                        OwningAbility;                                     // 0x1268(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnOwningAbilityEnterHealStage(bool bCanHeal);
	void OnOwningAbilityResurrectSelf(int32 ResurrectCount);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MarvelCueNotify_Ability_10490101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MarvelCueNotify_Ability_10490101")
	}
	static class AMarvelCueNotify_Ability_10490101* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMarvelCueNotify_Ability_10490101>();
	}
};
DUMPER7_ASSERTS_AMarvelCueNotify_Ability_10490101;

// Class Hero_1049.Config_104911
// 0x00B8 (0x0150 - 0x0098)
class UConfig_104911 final : public UMarvelAbilityConfig
{
public:
	ETotalHealthType                              PercentDamageHealthType;                           // 0x0098(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, class UCurveFloat*>               DamagePercentCurveMap;                             // 0x00A0(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGameplayTag                           AngerValueType;                                    // 0x00F0(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, float>                            ExtraBaseDamagePercent;                            // 0x0100(0x0050)(BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_104911")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_104911")
	}
	static class UConfig_104911* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_104911>();
	}
};
DUMPER7_ASSERTS_UConfig_104911;

// Class Hero_1049.EffectiveComponent_10491101_Base
// 0x0000 (0x2040 - 0x2040)
class UEffectiveComponent_10491101_Base final : public UMarvelAgentEffectiveComponent
{
public:
	class UConfig_104911* GetConfig_104911();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EffectiveComponent_10491101_Base")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EffectiveComponent_10491101_Base")
	}
	static class UEffectiveComponent_10491101_Base* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffectiveComponent_10491101_Base>();
	}
};
DUMPER7_ASSERTS_UEffectiveComponent_10491101_Base;

// Class Hero_1049.Cue_Ability_Loop_104911
// 0x0100 (0x12C0 - 0x11C0)
class ACue_Ability_Loop_104911 final : public AMarvelCueNotify_Ability
{
public:
	class UFXSystemAsset*                         LeftNormalFX;                                      // 0x11C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         LeftFullAngerFX;                                   // 0x11C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         RightNormalFX;                                     // 0x11D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         RightFullAngerFX;                                  // 0x11D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   LeftFXSocketName;                                  // 0x11E0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   RightFXSocketName;                                 // 0x11EC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               LeftFXRelativeRotator;                             // 0x11F8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               RightFXRelativeRotator;                            // 0x1210(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class FName                                   AlphaParamName;                                    // 0x1228(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   DissolveParamName;                                 // 0x1234(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   MaterialParamName;                                 // 0x1240(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMaterialQuery                         AngerMaterialQuery;                                // 0x124C(0x0024)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AngerMaterialSlotName;                             // 0x1270(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_127C[0x4];                                     // 0x127C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               MID;                                               // 0x1280(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLastTimeWolverineIsFullAnger;                     // 0x1288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1289[0x7];                                     // 0x1289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AWolverineCharacter*                    WolverineCharacter;                                // 0x1290(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFXSystemComponent*                     LeftHandNormalFXComponent;                         // 0x1298(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFXSystemComponent*                     LeftHandFullAngerFXComponent;                      // 0x12A0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFXSystemComponent*                     RightHandNormalFXComponent;                        // 0x12A8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFXSystemComponent*                     RightHandFullAngerFXComponent;                     // 0x12B0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         WolverineFullAngerValue;                           // 0x12B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_12BC[0x4];                                     // 0x12BC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Ability_Loop_104911")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Ability_Loop_104911")
	}
	static class ACue_Ability_Loop_104911* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_104911>();
	}
};
DUMPER7_ASSERTS_ACue_Ability_Loop_104911;

// Class Hero_1049.Config_104921
// 0x01C0 (0x0258 - 0x0098)
class UConfig_104921 final : public UMarvelAbilityConfig
{
public:
	int32                                         RageBuffID;                                        // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RageBuffExtraDuration;                             // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FRageInfo_104921>               RageGainFromAbilityHit;                            // 0x00A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	struct FMarvelGameplayTagRequirements         AbilityHitTargetRequirements;                      // 0x00B0(0x0120)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<struct FRageInfo_104921>               RageGainFromAbilityCast;                           // 0x01D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         RageGainFromDamageInterval;                        // 0x01E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RageGainFromDamageEachTime;                        // 0x01E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           FullRageHairTag;                                   // 0x01E8(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           FullRageScreenFXTag;                               // 0x01F4(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RageValueThreshold;                                // 0x0200(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_204[0x4];                                      // 0x0204(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<int32>                                   FullRageSelfBuffIDs;                               // 0x0208(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_104921")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_104921")
	}
	static class UConfig_104921* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_104921>();
	}
};
DUMPER7_ASSERTS_UConfig_104921;

// Class Hero_1049.BuffAbility_10492101
// 0x0008 (0x1478 - 0x1470)
class UBuffAbility_10492101 : public UMarvelAttributeFallBaseAbility
{
public:
	class UCurveFloat*                            AttenuationSpeedCurve;                             // 0x1470(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	float GetAverageAttenuationSpeed() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffAbility_10492101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffAbility_10492101")
	}
	static class UBuffAbility_10492101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10492101>();
	}
};
DUMPER7_ASSERTS_UBuffAbility_10492101;

// Class Hero_1049.Ability_104921
// 0x0078 (0x2AB8 - 0x2A40)
class UAbility_104921 : public UMarvelGameplayAbility
{
public:
	struct FActiveGameplayEffectHandle            RageBuffHandle;                                    // 0x2A40(0x0008)(NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UConfig_104921*                         CachedMyConfig;                                    // 0x2A48(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UBuffAbility_10492101*                  CachedMyBuffAbilityCDO;                            // 0x2A50(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2A58[0x60];                                    // 0x2A58(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void AddPassiveRageMeter(float InValue);
	class UBuffAbility_10492101* GetMyBuffAbilityCDO();
	class UConfig_104921* GetMyConfig();
	void NotifyRemoveRage(const struct FGameplayEventData& Payload);
	void OnManuallyApplyDamage(class UGameplayAbility* InAbility, class AActor* InActor);
	void OnOwnerAbilityActivated(class UGameplayAbility* InAbility);
	void OnOwnerAbilityHit(class UGameplayAbility* InAbility, const struct FMarvelAbilityHitParams& HitParams, const TArray<struct FHitResult>& InHitResults);
	void OnOwnerCharacterDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnOwnerCharacterReborn(class AActor* InSourceActor, const struct FCharacterRebornParam& RebornParam);
	void OnOwnerTakeDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& InModifierParameterHandle);
	void UpdateFullRageSelfBuff(bool bFullRage);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_104921")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_104921")
	}
	static class UAbility_104921* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104921>();
	}
};
DUMPER7_ASSERTS_UAbility_104921;

// Class Hero_1049.BuffCue_10492101
// 0x0170 (0x1860 - 0x16F0)
class ABuffCue_10492101 final : public AMarvelCueNotify_Buff
{
public:
	class FName                                   RageMaterialParamName;                             // 0x16E8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AudioParamName;                                    // 0x16F4(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            AudioParamCurve;                                   // 0x1700(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RageReachToMaxAudioID;                             // 0x1708(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RageReachToZeroAudioID;                            // 0x170C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraComponent*                      FireMeshNiagara;                                   // 0x1710(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UNiagaraSystem*                         NS_FireMesh;                                       // 0x1718(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UNiagaraSystem*                         NS_FullRageInstantFX;                              // 0x1720(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFXSystemAsset*                         EndFX_WhenDeath;                                   // 0x1728(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TMap<class FName, class UCurveFloat*>         RageMeterToFXParameters;                           // 0x1730(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer                  ForceMaxAngerFXParamTags;                          // 0x1780(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TMap<class FName, class UCurveFloat*>         RageMeterToMaterialParameters;                     // 0x17E8(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	float                                         FireMeshLowAlphaValue;                             // 0x1838(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_183C[0x4];                                     // 0x183C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelBaseCharacter*                   OwningCharacter;                                   // 0x1840(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1848[0x14];                                    // 0x1848(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LastTimeRageValue;                                 // 0x185C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnOwnedTagUpdate(const struct FGameplayTag& TagUpdated, bool bTagExists);
	void OnRageReachToMax();
	void OnRageReachToZero();
	void UpdateAudioParametersByRage(float InValue);
	void UpdateFXParametersByRage(float InValue);
	void UpdateMaterialParametersByRage(float InValue);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffCue_10492101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffCue_10492101")
	}
	static class ABuffCue_10492101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuffCue_10492101>();
	}
};
DUMPER7_ASSERTS_ABuffCue_10492101;

// Class Hero_1049.AnimNotifyState_WolverineTimedNiagaraWithAngerParam
// 0x0058 (0x02A8 - 0x0250)
class UAnimNotifyState_WolverineTimedNiagaraWithAngerParam final : public UAnimNotifyState_TimedNiagaraEffectEx
{
public:
	TMap<class FName, class UCurveFloat*>         RageMeterToFXParameters;                           // 0x0250(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	class UNiagaraComponent*                      CachedSpawnNiagara;                                // 0x02A0(0x0008)(ExportObject, BlueprintReadOnly, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AnimNotifyState_WolverineTimedNiagaraWithAngerParam")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimNotifyState_WolverineTimedNiagaraWithAngerParam")
	}
	static class UAnimNotifyState_WolverineTimedNiagaraWithAngerParam* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotifyState_WolverineTimedNiagaraWithAngerParam>();
	}
};
DUMPER7_ASSERTS_UAnimNotifyState_WolverineTimedNiagaraWithAngerParam;

// Class Hero_1049.EffectiveComponent_10493101
// 0x0000 (0x2040 - 0x2040)
class UEffectiveComponent_10493101 final : public UMarvelAgentEffectiveComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EffectiveComponent_10493101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EffectiveComponent_10493101")
	}
	static class UEffectiveComponent_10493101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffectiveComponent_10493101>();
	}
};
DUMPER7_ASSERTS_UEffectiveComponent_10493101;

// Class Hero_1049.BuffAbility_10493101
// 0x0000 (0x1388 - 0x1388)
class UBuffAbility_10493101 final : public UMarvelEffectGameplayAbility
{
public:
	void OnWolverineParticipateKill();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffAbility_10493101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffAbility_10493101")
	}
	static class UBuffAbility_10493101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10493101>();
	}
};
DUMPER7_ASSERTS_UBuffAbility_10493101;

// Class Hero_1049.BuffCue_10493101
// 0x0080 (0x1770 - 0x16F0)
class ABuffCue_10493101 final : public AMarvelCueNotify_Buff
{
public:
	class UPoseableMeshComponent*                 PoseMesh;                                          // 0x16E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPoseableMeshComponent*                 WeaponMesh;                                        // 0x16F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UMaterialInterface*                     AllyPerspectiveMaterial;                           // 0x16F8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UMaterialInterface*                     EnemyPerspectiveMaterial;                          // 0x1700(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnemyShouldSee;                                   // 0x1708(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1709[0x3];                                     // 0x1709(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PassedTime;                                        // 0x170C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TotalTime;                                         // 0x1710(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1714[0x4];                                     // 0x1714(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, struct FSpecialMeshHideBoneSetting> HeroMeshSpecialSettings;                         // 0x1718(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	uint8                                         Pad_1768[0x8];                                     // 0x1768(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffCue_10493101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffCue_10493101")
	}
	static class ABuffCue_10493101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuffCue_10493101>();
	}
};
DUMPER7_ASSERTS_ABuffCue_10493101;

// Class Hero_1049.Cue_HitImpact_10494101
// 0x0008 (0x08C0 - 0x08B8)
class UCue_HitImpact_10494101 final : public UMarvelCueNotify_MeleeHitImpact
{
public:
	int32                                         NormalAudioID;                                     // 0x08B8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FullRageAudioID;                                   // 0x08BC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_HitImpact_10494101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_HitImpact_10494101")
	}
	static class UCue_HitImpact_10494101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCue_HitImpact_10494101>();
	}
};
DUMPER7_ASSERTS_UCue_HitImpact_10494101;

// Class Hero_1049.AnimNotify_WolverinePlayNiagaraByAnger
// 0x00A0 (0x0420 - 0x0380)
class UAnimNotify_WolverinePlayNiagaraByAnger final : public UAnimNotify_PlayNiagaraEffectEx
{
public:
	TSoftObjectPtr<class UNiagaraSystem>          NormalFX;                                          // 0x0380(0x0030)(Edit, BlueprintVisible, BlueprintReadOnly, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UNiagaraSystem>          FullAngerFX;                                       // 0x03B0(0x0030)(Edit, BlueprintVisible, BlueprintReadOnly, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UNiagaraSystem>          SynergyFX;                                         // 0x03E0(0x0030)(Edit, BlueprintVisible, BlueprintReadOnly, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsWolverineFullAnger;                             // 0x0410(0x0001)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_411[0xF];                                      // 0x0411(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AnimNotify_WolverinePlayNiagaraByAnger")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimNotify_WolverinePlayNiagaraByAnger")
	}
	static class UAnimNotify_WolverinePlayNiagaraByAnger* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotify_WolverinePlayNiagaraByAnger>();
	}
};
DUMPER7_ASSERTS_UAnimNotify_WolverinePlayNiagaraByAnger;

// Class Hero_1049.Config_104951
// 0x0EE8 (0x0F80 - 0x0098)
class UConfig_104951 final : public UMarvelAbilityConfig
{
public:
	struct FDashAbilityInfo                       DashAbilityInfo;                                   // 0x0098(0x0EE8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_104951")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_104951")
	}
	static class UConfig_104951* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_104951>();
	}
};
DUMPER7_ASSERTS_UConfig_104951;

// Class Hero_1049.Ability_104951
// 0x0020 (0x2A68 - 0x2A48)
class UAbility_104951 : public UAbility_108
{
public:
	TMulticastInlineDelegate<void(ERushState_104951 CurrentState)> OnStateChangeDelegate;            // 0x2A48(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	ERushState_104951                             CurrentState;                                      // 0x2A58(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2A59[0x7];                                     // 0x2A59(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarvelAbilityTask_Dash*                DashTask;                                          // 0x2A60(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void ForceAnimIntoFall();
	ERushState_104951 GetCurrentState();
	void OnDashFinish(EDashStopReason InReason);
	void OnRep_CurrentState();
	void SetCurrentState(ERushState_104951 NewStat);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_104951")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_104951")
	}
	static class UAbility_104951* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104951>();
	}
};
DUMPER7_ASSERTS_UAbility_104951;

// Class Hero_1049.Cue_Ability_Loop_10495101
// 0x00C0 (0x1280 - 0x11C0)
class ACue_Ability_Loop_10495101 final : public AMarvelCueNotify_Ability
{
public:
	class UFXSystemAsset*                         SmokeTemplate;                                     // 0x11C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                SmokeLocationOffset;                               // 0x11C8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               SmokeRotationOffset;                               // 0x11E0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         Attack01Template;                                  // 0x11F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Attack01LocationOffset;                            // 0x1200(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Attack01RotationOffset;                            // 0x1218(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         Attack02Template;                                  // 0x1230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Attack02LocationOffset;                            // 0x1238(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Attack02RotationOffset;                            // 0x1250(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class AMarvelBaseCharacter*                   WolverineCharacter;                                // 0x1268(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAbility_104951*                        WolverineAbility;                                  // 0x1270(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1278[0x8];                                     // 0x1278(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnWolverineStateChange(ERushState_104951 InState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Ability_Loop_10495101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Ability_Loop_10495101")
	}
	static class ACue_Ability_Loop_10495101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10495101>();
	}
};
DUMPER7_ASSERTS_ACue_Ability_Loop_10495101;

// Class Hero_1049.WolverineMoveLogicBaseComponent
// 0x0000 (0x0488 - 0x0488)
class UWolverineMoveLogicBaseComponent final : public UMarvelMoveLogicBaseComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("WolverineMoveLogicBaseComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WolverineMoveLogicBaseComponent")
	}
	static class UWolverineMoveLogicBaseComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWolverineMoveLogicBaseComponent>();
	}
};
DUMPER7_ASSERTS_UWolverineMoveLogicBaseComponent;

// Class Hero_1049.BuffCue_10496101
// 0x0020 (0x1710 - 0x16F0)
class ABuffCue_10496101 : public AMarvelCueNotify_Buff
{
public:
	class UMaterialInterface*                     MetalMaterial;                                     // 0x16E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHiddenOriginalMesh;                               // 0x16F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16F1[0x7];                                     // 0x16F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarvelShellMeshComponent*              ShellComponent;                                    // 0x16F8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1700[0x10];                                    // 0x1700(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffCue_10496101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffCue_10496101")
	}
	static class ABuffCue_10496101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuffCue_10496101>();
	}
};
DUMPER7_ASSERTS_ABuffCue_10496101;

// Class Hero_1049.Config_104971
// 0x0120 (0x01B8 - 0x0098)
class UConfig_104971 : public UMarvelAbilityConfig
{
public:
	int32                                         GrabbedTargetCount;                                // 0x0098(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GrabbedScopeID;                                    // 0x009C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GrabbedDistanceCheckThreshold;                     // 0x00A0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWolverineShiftJumpParam               JumpParam;                                         // 0x00A8(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic)
	ETriggerSpecialLeftTime                       TriggerSpecialLeftTime;                            // 0x0100(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<int32>                                   SpecialLeftBuffSet;                                // 0x0108(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FLogicValueConfigCollection            LogicValue_Skill;                                  // 0x0158(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FLogicValueConfigCollection            LogicValue_AfterHit;                               // 0x0178(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FLogicValueConfigCollection            LogicValue_JumpDown;                               // 0x0198(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_104971")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_104971")
	}
	static class UConfig_104971* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_104971>();
	}
};
DUMPER7_ASSERTS_UConfig_104971;

// Class Hero_1049.Ability_104991
// 0x0150 (0x3448 - 0x32F8)
class UAbility_104991 : public UAbility_100015
{
public:
	struct FGameplayTag                           MarkOnHulkTag;                                     // 0x32F8(0x000C)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3304[0x4];                                     // 0x3304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(EWolverineSynergyState NewState)> OnWolverineSynergyStateChangeDispatcher; // 0x3308(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	EWolverineSynergyState                        CurrentState;                                      // 0x3318(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3319[0x7];                                     // 0x3319(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelBaseCharacter*                   Hulk;                                              // 0x3320(0x0008)(BlueprintVisible, Net, ZeroConstructor, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3328[0x90];                                    // 0x3328(0x0090)(Fixing Size After Last Property [ Dumper-7 ])
	class AWolverineChildActor*                   WolverineChildActor;                               // 0x33B8(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UConfig_104991*                         RideConfig;                                        // 0x33C0(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FPredictionKey                         DashKey;                                           // 0x33C8(0x0070)(Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHasBeenThrowed;                                   // 0x3438(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3439[0x7];                                     // 0x3439(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        OwnerCapsuleAttachParent;                          // 0x3440(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void BindCameraToRideCharacter(class AMarvelBaseCharacter* RideCharacter, bool bBind);
	void BindDettachDelegates(class AActor* InHulk);
	void BindOwnerCapsuleAttachParentChildDetachDelegate(bool bBind);
	void MarkOnHulk(bool bOnGroot);
	void OnHulkDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnHulkRepToSimulatedRole();
	void OnHulkTagUpdated(const struct FGameplayTag& TagUpdated, bool bTagExists);
	void OnOwnerCapsuleAttachParentChildDetach(class USceneComponent* SourceComponent, class USceneComponent* ChildComponent);
	void OnRep_CurrentState();
	void OnRep_Hulk();
	void OnWolverineDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnWolverineTagUpdated(const struct FGameplayTag& TagUpdated, bool bTagExists);
	void OnWolverineTakeDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void Python_AttachToHulk();
	void Python_DetachFromHulk();
	void Python_FailedFlyingToHulk();
	void Python_StartFlyingToHulk();
	void SetSpringArmIgnore(class AMarvelBaseCharacter* InHulk, class AMarvelBaseCharacter* OwnChar, bool bIgnore);
	void SetSynergyState(EWolverineSynergyState InState);
	void UnBindDettachDelegates(class AActor* InHulk);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_104991")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_104991")
	}
	static class UAbility_104991* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104991>();
	}
};
DUMPER7_ASSERTS_UAbility_104991;

// Class Hero_1049.Ability_104971
// 0x0338 (0x2D78 - 0x2A40)
class UAbility_104971 : public UMarvelGameplayAbility
{
public:
	class AWolverineCharacter*                    OwnerCharacter;                                    // 0x2A40(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPredictionKey                         ReplicateLaunchVelocityKey;                        // 0x2A48(0x0070)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPredictionKey                         SetLaunchParamKey;                                 // 0x2AB8(0x0070)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPredictionKey                         SetHitTargetParamKey;                              // 0x2B28(0x0070)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPredictionKey                         ServerNotifyGrabFailedRPCKey;                      // 0x2B98(0x0070)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPredictionKey                         ServerNotifyShiftLaunchedRPCKey;                   // 0x2C08(0x0070)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FPredictionKey                         ResetKey;                                          // 0x2C78(0x0070)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelBaseAbilitySystemComponent*      ASC;                                               // 0x2CE8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UWolverineMovementComponent*            OwnerMoveComp;                                     // 0x2CF0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConfig_104971*                         Config;                                            // 0x2CF8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSet<class ACharacter*>                       MoveIgnoreCharacterSet;                            // 0x2D00(0x0050)(NativeAccessSpecifierPublic)
	uint8                                         Pad_2D50[0x1];                                     // 0x2D50(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bHitTarget;                                        // 0x2D51(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERushState_104971                             CurrentState;                                      // 0x2D52(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bServerHasEnterEndState;                           // 0x2D53(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnterDropDown;                                    // 0x2D54(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnterEndState;                                    // 0x2D55(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bShiftJumpLaunched;                                // 0x2D56(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2D57[0x1];                                     // 0x2D57(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ACharacter*>                     GrabbedTargets;                                    // 0x2D58(0x0010)(BlueprintVisible, Net, ZeroConstructor, RepNotify, Protected, NativeAccessSpecifierProtected)
	bool                                          bSpecialLeftStatusApplied;                         // 0x2D68(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2D69[0x7];                                     // 0x2D69(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarvelAbilityTask_WaitTargetData*      ServerWaitGrabTargetTask;                          // 0x2D70(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void AddMoveIgnoreActor(class ACharacter* InActor);
	struct FVector CalcShiftJumpVelocity();
	ERushState_104971 GetCurrentState();
	void K2_ApplySpecialLeftStatus();
	void K2_EnterEndState();
	void K2_OnShiftJumpLaunched();
	bool K2_ShouldEndScope();
	void LaunchCharacter();
	void MulticastEnterDropDown();
	void OnHitTarget();
	void OnPredictingClientGrabTargetPredictFailed(class ACharacter* InCharacter);
	void OnRep_bServerHasEnterEndState();
	void OnRep_CurrentState();
	void OnRep_GrabbedTargets();
	void OnServerReceiveGrabTarget(const struct FGameplayAbilityTargetDataHandle& Data);
	void OnServerReceiveLaunchVelocity(const struct FGameplayAbilityTargetDataHandle& Data);
	void OnServerShiftLaunched();
	void OnServerWaitLaunchVelocityTimeout();
	void RegisterGrabTarget(class ACharacter* InTarget);
	void RemoveAllMoveIgnoreCharacters();
	void RemoveMoveIgnoreActor(class ACharacter* InActor);
	void ResetShiftJumpParameters(bool bUsePredictionKey);
	void RollBackMoveLogic();
	void SetCurrentState(ERushState_104971 NewStat);
	void SetupShiftJumpParameters(struct FVector* InVelocity);
	void TryGrabTarget(class ACharacter* InTarget);
	void UpdateShiftJumpUpState(float DeltaSeconds, const struct FVector& OldLocation, const struct FVector& OldVelocity);

	struct FVector GetGrabbedRelativeLocation(class ACharacter* InTarget, const struct FVector& OriginRelativeLocation) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_104971")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_104971")
	}
	static class UAbility_104971* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104971>();
	}
};
DUMPER7_ASSERTS_UAbility_104971;

// Class Hero_1049.Ability_104981
// 0x0030 (0x2A70 - 0x2A40)
class UAbility_104981 : public UMarvelGameplayAbility
{
public:
	TMulticastInlineDelegate<void(EAbilityStatus_104981 NewStatus)> AbilityStatusChangeDispatcher;   // 0x2A40(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	struct FVector                                SelectHitNormal;                                   // 0x2A50(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAbilityStatus_104981                         CurrentStatus;                                     // 0x2A68(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2A69[0x7];                                     // 0x2A69(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_CurrentStatus();
	void SetCurrentStatus(EAbilityStatus_104981 InStatus);

	EAbilityStatus_104981 GetCurrentStatus() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_104981")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_104981")
	}
	static class UAbility_104981* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104981>();
	}
};
DUMPER7_ASSERTS_UAbility_104981;

// Class Hero_1049.Cue_Buff_10498105
// 0x0030 (0x1720 - 0x16F0)
class ACue_Buff_10498105 final : public AMarvelCueNotify_Buff
{
public:
	class UMaterialInterface*                     AfterImageMaterial;                                // 0x16E8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPoseableMeshComponent*                 PoseMesh;                                          // 0x16F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UPoseableMeshComponent*                 WeaponMesh;                                        // 0x16F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TimeInterval;                                      // 0x1700(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1704[0x4];                                     // 0x1704(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           LoopTimerHandle;                                   // 0x1708(0x0018)(Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void UpdatePoseMesh(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Buff_10498105")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Buff_10498105")
	}
	static class ACue_Buff_10498105* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Buff_10498105>();
	}
};
DUMPER7_ASSERTS_ACue_Buff_10498105;

// Class Hero_1049.MarvelCueNotify_TraceActor_10498101
// 0x0000 (0x0FF0 - 0x0FF0)
class AMarvelCueNotify_TraceActor_10498101 final : public AMarvelCueNotify_TraceActor
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MarvelCueNotify_TraceActor_10498101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MarvelCueNotify_TraceActor_10498101")
	}
	static class AMarvelCueNotify_TraceActor_10498101* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMarvelCueNotify_TraceActor_10498101>();
	}
};
DUMPER7_ASSERTS_AMarvelCueNotify_TraceActor_10498101;

// Class Hero_1049.WolverineCharacter
// 0x0060 (0x2310 - 0x22B0)
class AWolverineCharacter : public AMarvelBaseCharacter
{
public:
	class URideOnCharacterManagementComponent*    SynergyRideManagementComponent;                    // 0x22B0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 CurrentState)> OnStateChangeDelegate;                        // 0x22B8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	bool                                          bHoldingForResurrectAbility;                       // 0x22C8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22C9[0x7];                                     // 0x22C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWolverineMoveLogicBaseComponent*       WolverineMoveLogic;                                // 0x22D0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FTimerHandle                           DelayActivateTimerHandle;                          // 0x22D8(0x0018)(Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTag                           AngerValueType;                                    // 0x22F0(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22FC[0x4];                                     // 0x22FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              WolverineParticipateInKillEventDispatcher;         // 0x2300(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	void CanResurrectSelfExternal(bool* Result);
	void DispatchWolverineParticipateKillEvent();

	float GetWolverineAngerCurrent() const;
	float GetWolverineAngerFull() const;
	bool IsWolverineAngerFull() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("WolverineCharacter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WolverineCharacter")
	}
	static class AWolverineCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWolverineCharacter>();
	}
};
DUMPER7_ASSERTS_AWolverineCharacter;

// Class Hero_1049.MarvelCueNotify_Ability_10498101
// 0x0030 (0x11F0 - 0x11C0)
class AMarvelCueNotify_Ability_10498101 final : public AMarvelCueNotify_Ability
{
public:
	TMulticastInlineDelegate<void()>              OnHideMaterialParamDispatcher;                     // 0x11C0(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	int32                                         DashLoopAudioID;                                   // 0x11D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11D4[0x14];                                    // 0x11D4(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelBaseCharacter*                   TargetCharacter;                                   // 0x11E8(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnAbilityStatusChanged(EAbilityStatus_104981 InStatus);
	void OnOwnedTagUpdate(const struct FGameplayTag& TagUpdated, bool bTagExists);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MarvelCueNotify_Ability_10498101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MarvelCueNotify_Ability_10498101")
	}
	static class AMarvelCueNotify_Ability_10498101* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMarvelCueNotify_Ability_10498101>();
	}
};
DUMPER7_ASSERTS_AMarvelCueNotify_Ability_10498101;

// Class Hero_1049.Cue_Scope_Start_10498101
// 0x0000 (0x0478 - 0x0478)
class UCue_Scope_Start_10498101 final : public UMarvelCueNotify_StaticScope
{
public:
	void OnSpawnedInstantNiagara(class UNiagaraComponent* InNSComponent, const class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Scope_Start_10498101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Scope_Start_10498101")
	}
	static class UCue_Scope_Start_10498101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCue_Scope_Start_10498101>();
	}
};
DUMPER7_ASSERTS_UCue_Scope_Start_10498101;

// Class Hero_1049.Config_104991
// 0x13B0 (0x32C0 - 0x1F10)
class UConfig_104991 : public UConfig_100015
{
public:
	struct FDashAbilityInfo                       DashToTargetInfo;                                  // 0x1F10(0x0EE8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         DashDurationBuffID;                                // 0x2DF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2DFC[0x4];                                     // 0x2DFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  BlockAbilityTagsWhenFlying;                        // 0x2E00(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          bBindCameraToRidingCharacter;                      // 0x2E68(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2E69[0x7];                                     // 0x2E69(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  BlockAbilityTagsWhenRiding;                        // 0x2E70(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TMap<int32, class FName>                      SocketNameMap;                                     // 0x2ED8(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  TargetDetachTagContainer;                          // 0x2F28(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  WolverineDetachTagContainer;                       // 0x2F90(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UCameraInterp*                          RidingCameraInterp;                                // 0x2FF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExitRideWhenWolverineTakeDamage;                  // 0x3000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3001[0x7];                                     // 0x3001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<int32>                                   SameBuffSet;                                       // 0x3008(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FRideSameBuffInfo                      SameBuffInfo;                                      // 0x3058(0x00F0)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  RemoveEffectWithTagsWhileAttach;                   // 0x3148(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FVector                                AttachCylinderOffset;                              // 0x31B0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                AttachMeshOffset;                                  // 0x31C8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  SkipCameraBlendTags;                               // 0x31E0(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	float                                         DetachCameraBlendTime;                             // 0x3248(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_324C[0x4];                                     // 0x324C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  ThrowAbilityTagContainer;                          // 0x3250(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	uint8                                         Pad_32B8[0x8];                                     // 0x32B8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_104991")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_104991")
	}
	static class UConfig_104991* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_104991>();
	}
};
DUMPER7_ASSERTS_UConfig_104991;

// Class Hero_1049.Cue_Ability_Loop_10499101
// 0x0130 (0x12F0 - 0x11C0)
class ACue_Ability_Loop_10499101 : public AMarvelCueNotify_Ability
{
public:
	float                                         StopRideSoundID;                                   // 0x11C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11C4[0x4];                                     // 0x11C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         NS_AttachInstantFX;                                // 0x11C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraSystem*                         NS_AttachInstantFX_Horizontal;                     // 0x11D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               AttachInstantFX_Horizontal_Rotator;                // 0x11D8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	TMap<int32, class FName>                      AttachInstantFXSocketMap;                          // 0x11F0(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class AMarvelBaseCharacter*                   OwningCharacter;                                   // 0x1240(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAbility_104991*                        CoopAbility;                                       // 0x1248(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCameraInterp*                          RidingCameraInterp;                                // 0x1250(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TMap<class AActor*, struct FSpringArmControlHandler> SpringArmHandlers;                          // 0x1258(0x0050)(Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_12A8[0x18];                                    // 0x12A8(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnSynergyFlyDispatcher;                            // 0x12C0(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnSynergyAttachDispatcher;                         // 0x12D0(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnSynergyDetachDispatcher;                         // 0x12E0(0x0010)(ZeroConstructor, Transient, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	void OnCoopStateChange(EWolverineSynergyState InState);
	void PlayAttachInstantFX();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Ability_Loop_10499101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Ability_Loop_10499101")
	}
	static class ACue_Ability_Loop_10499101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10499101>();
	}
};
DUMPER7_ASSERTS_ACue_Ability_Loop_10499101;

// Class Hero_1049.BuffCue_10499401
// 0x0040 (0x1730 - 0x16F0)
class ABuffCue_10499401 final : public AMarvelCueNotify_Buff
{
public:
	struct FGameplayTag                           HideNiagaraTag;                                    // 0x16E8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16F4[0x4];                                     // 0x16F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      MaxAngerFireMeshNiagara;                           // 0x16F8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           CueTag_104921;                                     // 0x1700(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_170C[0x14];                                    // 0x170C(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UNiagaraComponent*>              DynamicUpdateHiddenInGameComponents;               // 0x1720(0x0010)(ExportObject, ZeroConstructor, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)

public:
	void OnOwnedTagUpdate(const struct FGameplayTag& TagUpdated, bool bTagExists);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffCue_10499401")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffCue_10499401")
	}
	static class ABuffCue_10499401* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuffCue_10499401>();
	}
};
DUMPER7_ASSERTS_ABuffCue_10499401;

// Class Hero_1049.WolverineAnimInstance
// 0x02D0 (0x0CF0 - 0x0A20)
class UWolverineAnimInstance final : public UMarvelAnimInstance
{
public:
	float                                         DelayExitShiftBlendTime;                           // 0x0A20(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnterMouseRight;                                  // 0x0A24(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bExitMouseRight;                                   // 0x0A25(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bMouseRightForceToGroundMotion;                    // 0x0A26(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_A27[0x1];                                      // 0x0A27(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CurrentPitchAngle;                                 // 0x0A28(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnterShift;                                       // 0x0A2C(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bExitShift;                                        // 0x0A2D(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bShiftToNormal;                                    // 0x0A2E(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bShiftEndBlendUpperBody;                           // 0x0A2F(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bShiftForceToGroundMotion;                         // 0x0A30(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bInSynergyRideState;                               // 0x0A31(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_A32[0x2];                                      // 0x0A32(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SynergyRidePosition;                               // 0x0A34(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHulkRunning;                                      // 0x0A38(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHulkGatheringToThrow;                             // 0x0A39(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_A3A[0x6];                                      // 0x0A3A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, struct FWolverineSynergyRideAnimationData> SynergyAnimationDataMap;                  // 0x0A40(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, Protected, NativeAccessSpecifierProtected)
	TMap<int32, float>                            SynergyAnimationRatioMap;                          // 0x0A90(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, Protected, NativeAccessSpecifierProtected)
	TMap<int32, struct FWolverineSynergyAnimationRatioSpeedUpInfo> SynergyAnimationRatioAnimationMap; // 0x0AE0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, Protected, NativeAccessSpecifierProtected)
	struct FWolverineSynergyRideAnimBlendData     SynergyRideLoopAnimBlendData;                      // 0x0B30(0x0038)(BlueprintVisible, BlueprintReadOnly, Transient, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FWolverineSynergyRideAnimBlendData     SynergyRideGatherAnimBlendData;                    // 0x0B68(0x0038)(BlueprintVisible, BlueprintReadOnly, Transient, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_BA0[0x38];                                     // 0x0BA0(0x0038)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWolverineSynergyRideAnimBlendData     SynergyRideLoopAnimBlendData_TS;                   // 0x0BD8(0x0038)(Transient, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FWolverineSynergyRideAnimBlendData     SynergyRideGatherAnimBlendData_TS;                 // 0x0C10(0x0038)(Transient, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_C48[0xA8];                                     // 0x0C48(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnMouseRightStateChanged(ERushState_104951 CurrentState);
	void OnShiftStateChanged(int32 InState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("WolverineAnimInstance")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WolverineAnimInstance")
	}
	static class UWolverineAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWolverineAnimInstance>();
	}
};
DUMPER7_ASSERTS_UWolverineAnimInstance;

// Class Hero_1049.WolverineChildActor
// 0x01A0 (0x0FD0 - 0x0E30)
class AWolverineChildActor final : public AMarvelCharacterChildActor
{
public:
	TArray<struct FMaterialQuery>                 MaxAngerHairMaterialMaterialQuery;                 // 0x0E28(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FMaterialQuery>                 HideWhenMaxAngerMaterialQuery;                     // 0x0E38(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	class FName                                   MaxAngerHairMaterialSlotNameSuffix;                // 0x0E48(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   HideWhenMaxAngerSlotNameSuffix;                    // 0x0E54(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ShowMaxAngerHairTag;                               // 0x0E60(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E6C[0x4];                                      // 0x0E6C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, class UCurveFloat*>         ShowHairCurveMap;                                  // 0x0E70(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TMap<class FName, class UCurveFloat*>         HideHairCurveMap;                                  // 0x0EC0(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UNiagaraSystem*                         NS_ShowFireHair;                                   // 0x0F10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HideHariTime;                                      // 0x0F18(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShowNormalHairTime;                                // 0x0F1C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTimerHandle                           ShowNormalHairTimerHandle;                         // 0x0F20(0x0018)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AccumulateHairTime;                                // 0x0F38(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShowFireHair;                                     // 0x0F3C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F3D[0x3];                                      // 0x0F3D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      FireHairNiagara;                                   // 0x0F40(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FName, class UCurveFloat*>         NormalHairCurveMap;                                // 0x0F48(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	float                                         AccumulateNormalHairTime;                          // 0x0F98(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNormalHairVisible;                                // 0x0F9C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F9D[0x1B];                                     // 0x0F9D(0x001B)(Fixing Size After Last Property [ Dumper-7 ])
	class AWolverineCharacter*                    WolverineOwner;                                    // 0x0FB8(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsHairMaterialShowed;                             // 0x0FC0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_FC1[0xF];                                      // 0x0FC1(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnHairTagUpdated(const struct FGameplayTag& InTag, bool bInExist);
	void OnWolverineMeshMaterialChanged();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("WolverineChildActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WolverineChildActor")
	}
	static class AWolverineChildActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWolverineChildActor>();
	}
};
DUMPER7_ASSERTS_AWolverineChildActor;

// Class Hero_1049.WolverineMovementComponent
// 0x0080 (0x2470 - 0x23F0)
class UWolverineMovementComponent final : public UMarvelCharacterMovementComponent
{
public:
	bool                                          bBlendAccelerationByCameraDir;                     // 0x23F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_23F1[0x3];                                     // 0x23F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BlendFactor;                                       // 0x23F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AMarvelBaseCharacter*                   WolverineCharacter;                                // 0x23F8(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer                  SpecialJumpAbilityTags;                            // 0x2400(0x0068)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	uint8                                         Pad_2468[0x8];                                     // 0x2468(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetBlendAccelerationByCameraDirection(bool bBlend, float InBlendFactor);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("WolverineMovementComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WolverineMovementComponent")
	}
	static class UWolverineMovementComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWolverineMovementComponent>();
	}
};
DUMPER7_ASSERTS_UWolverineMovementComponent;

}

