#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mode_2201

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Hero_1021_structs.hpp"
#include "Engine_structs.hpp"
#include "Marvel_classes.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// Class Mode_2201.Cue_Buff_22010201
// 0x00B0 (0x17A0 - 0x16F0)
class ACue_Buff_22010201 : public AMarvelCueNotify_Buff
{
public:
	struct FGameplayTag                           BuffAbilityTag;                                    // 0x16E8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FirstTimeInterval;                                 // 0x16F4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FirstTimeChange;                                   // 0x16F8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SecondTimeInterval;                                // 0x16FC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SecondTimeChange;                                  // 0x1700(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   OpacityName;                                       // 0x1704(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            FirstOpacityCurve;                                 // 0x1710(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            SecondOpacityCurve;                                // 0x1718(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ExistingDuration;                                  // 0x1720(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ForceLOD;                                          // 0x1724(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInterface*                     AfterImageMaterial;                                // 0x1728(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInterface*                     AfterImageMaterialTargetPerspective;               // 0x1730(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           PoseMeshIgnoreTag;                                 // 0x1738(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           PoseMeshTargetTag;                                 // 0x1744(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTimerHandle                           LoopTimerHandle;                                   // 0x1750(0x0018)(Transient, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<struct FPoseMeshItem>                  PoseMeshPool;                                      // 0x1768(0x0010)(ZeroConstructor, Transient, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	class AMarvelBaseCharacter*                   OwnerCharacter;                                    // 0x1778(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UBuffAbility_BodySizeChange*            OwnerAbility;                                      // 0x1780(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MeshSizeChangeDelta;                               // 0x1788(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         CurrentMeshSize;                                   // 0x178C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TargetMeshSize;                                    // 0x1790(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bStartState;                                       // 0x1794(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1795[0xB];                                     // 0x1795(0x000B)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	int32 ApplyUsablePoseMesh();
	void ClearLoopTimer();
	bool IgnoreSetCustomStencil();
	void OnSetupAfterCom();
	void ResetPoseMeshPool();
	void SetLoopTimer();
	void UpdatePoseMesh(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Buff_22010201")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Buff_22010201")
	}
	static class ACue_Buff_22010201* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Buff_22010201>();
	}
};
DUMPER7_ASSERTS_ACue_Buff_22010201;

// Class Mode_2201.M2201PlayerEmoteComponent
// 0x00A8 (0x01B0 - 0x0108)
class UM2201PlayerEmoteComponent : public UMarvelActorComponentBase
{
public:
	class AMarvelBaseCharacter*                   OwnerCharacter;                                    // 0x0108(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TWeakObjectPtr<class UAbilitySystemComponent> AbilitySystemComponent;                            // 0x0110(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_118[0x50];                                     // 0x0118(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	ENetRole                                      MovementUpdatedNotAvailableRemoteRole;             // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bMovementUpdatedCheckFalling;                      // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_16A[0x3E];                                     // 0x016A(0x003E)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarvelAeroBaseAbility*                 AeroAbility;                                       // 0x01A8(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void K2_OnAbilityActivate(class UGameplayAbility* ActivatedAbility);
	void K2_OnCharacterMoved();
	void K2_OnGenericGameplayTagUpdate(const struct FGameplayTag& InTag, int32 Count);
	void OnAbilityActivate(class UGameplayAbility* ActivatedAbility);
	void OnCharacterMoved();
	void OnGenericGameplayTagUpdate(const struct FGameplayTag& InTag, int32 Count);
	void OnMovementUpdated(float DeltaTime, const struct FVector& OldLocation, const struct FVector& OldVelocity);
	void RegisterCharacterMovementUpdatedEvents();
	void RegisterEventTag(const struct FGameplayTag& InTag, EGameplayTagEventType EventType);
	void UnregisterCharacterMovementUpdatedEvents();
	void UnregisterEventTags();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("M2201PlayerEmoteComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"M2201PlayerEmoteComponent")
	}
	static class UM2201PlayerEmoteComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UM2201PlayerEmoteComponent>();
	}
};
DUMPER7_ASSERTS_UM2201PlayerEmoteComponent;

}

