#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NotTreatShield_10466108_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NotTreatShield_10466108_BP.NotTreatShield_10466108_BP_C
// 0x0000 (0x1540 - 0x1540)
class UNotTreatShield_10466108_BP_C final : public UMarvelNotTreatFallAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NotTreatShield_10466108_BP_C">();
	}
	static class UNotTreatShield_10466108_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNotTreatShield_10466108_BP_C>();
	}
};
static_assert(alignof(UNotTreatShield_10466108_BP_C) == 0x000008, "Wrong alignment on UNotTreatShield_10466108_BP_C");
static_assert(sizeof(UNotTreatShield_10466108_BP_C) == 0x001540, "Wrong size on UNotTreatShield_10466108_BP_C");

}

