#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerformanceGraphicSettingKey

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct PerformanceGraphicSettingKey.PerformanceGraphicSettingKey
// 0x0010 (0x0010 - 0x0000)
struct FPerformanceGraphicSettingKey final
{
public:
	class FString                                 TableRowName_3_F065C96D4C7D9CB34D461D818CF16BE8;   // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(FPerformanceGraphicSettingKey) == 0x000008, "Wrong alignment on FPerformanceGraphicSettingKey");
static_assert(sizeof(FPerformanceGraphicSettingKey) == 0x000010, "Wrong size on FPerformanceGraphicSettingKey");
static_assert(offsetof(FPerformanceGraphicSettingKey, TableRowName_3_F065C96D4C7D9CB34D461D818CF16BE8) == 0x000000, "Member 'FPerformanceGraphicSettingKey::TableRowName_3_F065C96D4C7D9CB34D461D818CF16BE8' has a wrong offset!");

}

