#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PracticeRange_Art

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PracticeRange_Art.PracticeRange_Art_C
// 0x0000 (0x0740 - 0x0740)
class APracticeRange_Art_C final : public AMarvelLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PracticeRange_Art_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PracticeRange_Art_C")
	}
	static class APracticeRange_Art_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APracticeRange_Art_C>();
	}
};
DUMPER7_ASSERTS_APracticeRange_Art_C;

}

