#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105611

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "Hero_1056_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// PythonClass PyAbility_105611.PyConfig_105611
// 0x00F0 (0x0188 - 0x0098)
class UPyConfig_105611 final : public UMarvelAbilityConfig
{
public:
	EAmmoClipType                                 EnergyType;                                        // 0x0098(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAmmoClipType                                 UIEnergyType;                                      // 0x0099(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9A[0x2];                                       // 0x009A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxEnergy;                                         // 0x009C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           SpecialFlyAbilityTag;                              // 0x00A0(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SpecialFlyTLIndex;                                 // 0x00AC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DefaultTLIndex;                                    // 0x00B0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            GligingSpeedOverflowDamageCurve;                   // 0x00B8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DeathClearEnergy;                                  // 0x00C0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C1[0x3];                                       // 0x00C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         EnergyCostCoff_Glide;                              // 0x00C4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EnergyCostCoff_Air;                                // 0x00C8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<EAmmoClipType>                           EnergyCostTypes;                                   // 0x00D0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	float                                         EnergyCostCoff;                                    // 0x0120(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Energy2DamageCoff;                                 // 0x0124(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Energy2DamageFullEnergy;                           // 0x0128(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HitCostEnergy;                                     // 0x012C(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12D[0x3];                                      // 0x012D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         KnockUpEnergyPercent;                              // 0x0130(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<EAngelaEnergyLevel, TSubclassOf<class ULegacyCameraShake>> HitCSMap;                        // 0x0138(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_105611">();
	}
	static class UPyConfig_105611* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_105611>();
	}
};
static_assert(alignof(UPyConfig_105611) == 0x000008, "Wrong alignment on UPyConfig_105611");
static_assert(sizeof(UPyConfig_105611) == 0x000188, "Wrong size on UPyConfig_105611");
static_assert(offsetof(UPyConfig_105611, EnergyType) == 0x000098, "Member 'UPyConfig_105611::EnergyType' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, UIEnergyType) == 0x000099, "Member 'UPyConfig_105611::UIEnergyType' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, MaxEnergy) == 0x00009C, "Member 'UPyConfig_105611::MaxEnergy' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, SpecialFlyAbilityTag) == 0x0000A0, "Member 'UPyConfig_105611::SpecialFlyAbilityTag' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, SpecialFlyTLIndex) == 0x0000AC, "Member 'UPyConfig_105611::SpecialFlyTLIndex' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, DefaultTLIndex) == 0x0000B0, "Member 'UPyConfig_105611::DefaultTLIndex' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, GligingSpeedOverflowDamageCurve) == 0x0000B8, "Member 'UPyConfig_105611::GligingSpeedOverflowDamageCurve' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, DeathClearEnergy) == 0x0000C0, "Member 'UPyConfig_105611::DeathClearEnergy' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, EnergyCostCoff_Glide) == 0x0000C4, "Member 'UPyConfig_105611::EnergyCostCoff_Glide' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, EnergyCostCoff_Air) == 0x0000C8, "Member 'UPyConfig_105611::EnergyCostCoff_Air' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, EnergyCostTypes) == 0x0000D0, "Member 'UPyConfig_105611::EnergyCostTypes' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, EnergyCostCoff) == 0x000120, "Member 'UPyConfig_105611::EnergyCostCoff' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, Energy2DamageCoff) == 0x000124, "Member 'UPyConfig_105611::Energy2DamageCoff' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, Energy2DamageFullEnergy) == 0x000128, "Member 'UPyConfig_105611::Energy2DamageFullEnergy' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, HitCostEnergy) == 0x00012C, "Member 'UPyConfig_105611::HitCostEnergy' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, KnockUpEnergyPercent) == 0x000130, "Member 'UPyConfig_105611::KnockUpEnergyPercent' has a wrong offset!");
static_assert(offsetof(UPyConfig_105611, HitCSMap) == 0x000138, "Member 'UPyConfig_105611::HitCSMap' has a wrong offset!");

// PythonClass PyAbility_105611.PyCue_Ability_Instant_10561101
// 0x0018 (0x03D8 - 0x03C0)
class UPyCue_Ability_Instant_10561101 final : public UMarvelCueNotify_Base
{
public:
	EAmmoClipType                                 Energy_Type;                                       // 0x03C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 FXParam;                                           // 0x03C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void SetNiagaraEnergyParam(class UNiagaraComponent* InNSComp, class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Instant_10561101">();
	}
	static class UPyCue_Ability_Instant_10561101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyCue_Ability_Instant_10561101>();
	}
};
static_assert(alignof(UPyCue_Ability_Instant_10561101) == 0x000008, "Wrong alignment on UPyCue_Ability_Instant_10561101");
static_assert(sizeof(UPyCue_Ability_Instant_10561101) == 0x0003D8, "Wrong size on UPyCue_Ability_Instant_10561101");
static_assert(offsetof(UPyCue_Ability_Instant_10561101, Energy_Type) == 0x0003C0, "Member 'UPyCue_Ability_Instant_10561101::Energy_Type' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_Instant_10561101, FXParam) == 0x0003C8, "Member 'UPyCue_Ability_Instant_10561101::FXParam' has a wrong offset!");

// PythonClass PyAbility_105611.PyEffectiveComponent_10561101
// 0x0000 (0x1C70 - 0x1C70)
class UPyEffectiveComponent_10561101 : public UMarvelAgentEffectiveComponent
{
public:
	TArray<struct FHitResult> K2_OnPreApplyContainer(const TArray<struct FHitResult>& HitResults);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyEffectiveComponent_10561101">();
	}
	static class UPyEffectiveComponent_10561101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyEffectiveComponent_10561101>();
	}
};
static_assert(alignof(UPyEffectiveComponent_10561101) == 0x000010, "Wrong alignment on UPyEffectiveComponent_10561101");
static_assert(sizeof(UPyEffectiveComponent_10561101) == 0x001C70, "Wrong size on UPyEffectiveComponent_10561101");

// PythonClass PyAbility_105611.PyEffectiveComponent_10561102
// 0x0000 (0x1C70 - 0x1C70)
class UPyEffectiveComponent_10561102 final : public UPyEffectiveComponent_10561101
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyEffectiveComponent_10561102">();
	}
	static class UPyEffectiveComponent_10561102* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyEffectiveComponent_10561102>();
	}
};
static_assert(alignof(UPyEffectiveComponent_10561102) == 0x000010, "Wrong alignment on UPyEffectiveComponent_10561102");
static_assert(sizeof(UPyEffectiveComponent_10561102) == 0x001C70, "Wrong size on UPyEffectiveComponent_10561102");

// PythonClass PyAbility_105611.PyAbility_105611
// 0x0000 (0x29F8 - 0x29F8)
class UPyAbility_105611 : public UAbility_108
{
public:
	void BeginPlay();
	void EndPlay();
	void OnOwnerDeath(class AActor* Source, class AActor* Target, const struct FAttributeModifierHandle& ModifierHandle);
	int32 GetTimelineIndexToPlay();
	void K2_ActivateAbility();
	void OnGameplayAbilityHit(const TArray<struct FHitResult>& HitResults);
	void MissileEventNotify();
	void BreakEventNotify();
	void ConsumeEnergy();
	void K2_OnEndAbility(bool bWasCancelled);
	TSubclassOf<class ULegacyCameraShake> GetCustomHitCS();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_105611">();
	}
	static class UPyAbility_105611* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_105611>();
	}
};
static_assert(alignof(UPyAbility_105611) == 0x000008, "Wrong alignment on UPyAbility_105611");
static_assert(sizeof(UPyAbility_105611) == 0x0029F8, "Wrong size on UPyAbility_105611");

// PythonClass PyAbility_105611.PyKnockUpAbility_10561101
// 0x0008 (0x2040 - 0x2038)
class UPyKnockUpAbility_10561101 : public UMarvelKnockUpAbility
{
public:
	bool                                          OpenGlidingExtraSpeed;                             // 0x2038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2039[0x3];                                     // 0x2039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GlidingExtraKnockSpeed;                            // 0x203C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	float GetForceMoveSpeed();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyKnockUpAbility_10561101">();
	}
	static class UPyKnockUpAbility_10561101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyKnockUpAbility_10561101>();
	}
};
static_assert(alignof(UPyKnockUpAbility_10561101) == 0x000008, "Wrong alignment on UPyKnockUpAbility_10561101");
static_assert(sizeof(UPyKnockUpAbility_10561101) == 0x002040, "Wrong size on UPyKnockUpAbility_10561101");
static_assert(offsetof(UPyKnockUpAbility_10561101, OpenGlidingExtraSpeed) == 0x002038, "Member 'UPyKnockUpAbility_10561101::OpenGlidingExtraSpeed' has a wrong offset!");
static_assert(offsetof(UPyKnockUpAbility_10561101, GlidingExtraKnockSpeed) == 0x00203C, "Member 'UPyKnockUpAbility_10561101::GlidingExtraKnockSpeed' has a wrong offset!");

// PythonClass PyAbility_105611.PyTraceComponent_10561102
// 0x0000 (0x2200 - 0x2200)
class UPyTraceComponent_10561102 final : public UMarvelAgentTraceComponent
{
public:
	struct FRotator K2_OnGetTraceRotator(struct FRotator& Rotator);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTraceComponent_10561102">();
	}
	static class UPyTraceComponent_10561102* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTraceComponent_10561102>();
	}
};
static_assert(alignof(UPyTraceComponent_10561102) == 0x000010, "Wrong alignment on UPyTraceComponent_10561102");
static_assert(sizeof(UPyTraceComponent_10561102) == 0x002200, "Wrong size on UPyTraceComponent_10561102");

// PythonClass PyAbility_105611.PyCue_Ability_HitImpact_10561101
// 0x0028 (0x05F0 - 0x05C8)
class UPyCue_Ability_HitImpact_10561101 final : public UMarvelCueNotify_HitImpact
{
public:
	EAmmoClipType                                 Energy_Type;                                       // 0x05C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5C9[0x7];                                      // 0x05C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 FXParam;                                           // 0x05D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          OpenStageHitAudio;                                 // 0x05E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5E1[0x3];                                      // 0x05E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LowEnergyHitAudio;                                 // 0x05E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HighEnergyHitAudio;                                // 0x05E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FullEnergyHitAudio;                                // 0x05EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PostSpawnNS(class UNiagaraComponent* InNSComp, class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

	int32 GetAbilityHitAudioID(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_HitImpact_10561101">();
	}
	static class UPyCue_Ability_HitImpact_10561101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyCue_Ability_HitImpact_10561101>();
	}
};
static_assert(alignof(UPyCue_Ability_HitImpact_10561101) == 0x000008, "Wrong alignment on UPyCue_Ability_HitImpact_10561101");
static_assert(sizeof(UPyCue_Ability_HitImpact_10561101) == 0x0005F0, "Wrong size on UPyCue_Ability_HitImpact_10561101");
static_assert(offsetof(UPyCue_Ability_HitImpact_10561101, Energy_Type) == 0x0005C8, "Member 'UPyCue_Ability_HitImpact_10561101::Energy_Type' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_HitImpact_10561101, FXParam) == 0x0005D0, "Member 'UPyCue_Ability_HitImpact_10561101::FXParam' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_HitImpact_10561101, OpenStageHitAudio) == 0x0005E0, "Member 'UPyCue_Ability_HitImpact_10561101::OpenStageHitAudio' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_HitImpact_10561101, LowEnergyHitAudio) == 0x0005E4, "Member 'UPyCue_Ability_HitImpact_10561101::LowEnergyHitAudio' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_HitImpact_10561101, HighEnergyHitAudio) == 0x0005E8, "Member 'UPyCue_Ability_HitImpact_10561101::HighEnergyHitAudio' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_HitImpact_10561101, FullEnergyHitAudio) == 0x0005EC, "Member 'UPyCue_Ability_HitImpact_10561101::FullEnergyHitAudio' has a wrong offset!");

// PythonClass PyAbility_105611.PyCue_Ability_MeleeHitImpact_10561101
// 0x0018 (0x0890 - 0x0878)
class UPyCue_Ability_MeleeHitImpact_10561101 final : public UMarvelCueNotify_MeleeHitImpact
{
public:
	EAmmoClipType                                 Energy_Type;                                       // 0x0878(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_879[0x7];                                      // 0x0879(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 FXParam;                                           // 0x0880(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PostSpawnNS(class UNiagaraComponent* InNSComp, class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_MeleeHitImpact_10561101">();
	}
	static class UPyCue_Ability_MeleeHitImpact_10561101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyCue_Ability_MeleeHitImpact_10561101>();
	}
};
static_assert(alignof(UPyCue_Ability_MeleeHitImpact_10561101) == 0x000008, "Wrong alignment on UPyCue_Ability_MeleeHitImpact_10561101");
static_assert(sizeof(UPyCue_Ability_MeleeHitImpact_10561101) == 0x000890, "Wrong size on UPyCue_Ability_MeleeHitImpact_10561101");
static_assert(offsetof(UPyCue_Ability_MeleeHitImpact_10561101, Energy_Type) == 0x000878, "Member 'UPyCue_Ability_MeleeHitImpact_10561101::Energy_Type' has a wrong offset!");
static_assert(offsetof(UPyCue_Ability_MeleeHitImpact_10561101, FXParam) == 0x000880, "Member 'UPyCue_Ability_MeleeHitImpact_10561101::FXParam' has a wrong offset!");

// PythonClass PyAbility_105611.PyWidget_AbilityEnergy_105611
// 0x0000 (0x05A0 - 0x05A0)
class UPyWidget_AbilityEnergy_105611 final : public UWidget_AbilityEnergy
{
public:
	void SetPercent(float InPercent);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_AbilityEnergy_105611">();
	}
	static class UPyWidget_AbilityEnergy_105611* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityEnergy_105611>();
	}
};
static_assert(alignof(UPyWidget_AbilityEnergy_105611) == 0x000008, "Wrong alignment on UPyWidget_AbilityEnergy_105611");
static_assert(sizeof(UPyWidget_AbilityEnergy_105611) == 0x0005A0, "Wrong size on UPyWidget_AbilityEnergy_105611");

// PythonClass PyAbility_105611.PyUIController_105611
// 0x0028 (0x0F38 - 0x0F10)
class UPyUIController_105611 final : public UUIC_Ability
{
public:
	EAmmoClipType                                 EnergyType;                                        // 0x0F10(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAmmoClipType                                 UIEnergyType;                                      // 0x0F11(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F12[0x2];                                      // 0x0F12(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         UpdateInterval;                                    // 0x0F14(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RtpcName;                                          // 0x0F18(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RtpcMax;                                           // 0x0F28(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EnergyGrowAudioID;                                 // 0x0F2C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EnergyHighLevelAudioID;                            // 0x0F30(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EnergyFullAudioID;                                 // 0x0F34(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void SetAbility(int32 InAbilityID, class UGameplayAbility* InAbility);
	void OnDestruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_105611">();
	}
	static class UPyUIController_105611* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_105611>();
	}
};
static_assert(alignof(UPyUIController_105611) == 0x000008, "Wrong alignment on UPyUIController_105611");
static_assert(sizeof(UPyUIController_105611) == 0x000F38, "Wrong size on UPyUIController_105611");
static_assert(offsetof(UPyUIController_105611, EnergyType) == 0x000F10, "Member 'UPyUIController_105611::EnergyType' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, UIEnergyType) == 0x000F11, "Member 'UPyUIController_105611::UIEnergyType' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, UpdateInterval) == 0x000F14, "Member 'UPyUIController_105611::UpdateInterval' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, RtpcName) == 0x000F18, "Member 'UPyUIController_105611::RtpcName' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, RtpcMax) == 0x000F28, "Member 'UPyUIController_105611::RtpcMax' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, EnergyGrowAudioID) == 0x000F2C, "Member 'UPyUIController_105611::EnergyGrowAudioID' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, EnergyHighLevelAudioID) == 0x000F30, "Member 'UPyUIController_105611::EnergyHighLevelAudioID' has a wrong offset!");
static_assert(offsetof(UPyUIController_105611, EnergyFullAudioID) == 0x000F34, "Member 'UPyUIController_105611::EnergyFullAudioID' has a wrong offset!");

}

