#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104994

#include "Basic.hpp"

#include "PyAbility_104971_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104994.PyConfig_104994
// 0x0008 (0x0520 - 0x0518)
class UPyConfig_104994 final : public UPyConfig_104971
{
public:
	int32                                         SynergyBurnScopeID;                                // 0x0518(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_104994">();
	}
	static class UPyConfig_104994* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104994>();
	}
};
static_assert(alignof(UPyConfig_104994) == 0x000008, "Wrong alignment on UPyConfig_104994");
static_assert(sizeof(UPyConfig_104994) == 0x000520, "Wrong size on UPyConfig_104994");
static_assert(offsetof(UPyConfig_104994, SynergyBurnScopeID) == 0x000518, "Member 'UPyConfig_104994::SynergyBurnScopeID' has a wrong offset!");

// PythonClass PyAbility_104994.PyAbility_104994
// 0x0000 (0x2D28 - 0x2D28)
class UPyAbility_104994 : public UPyAbility_104971
{
public:
	bool CanActivate();
	void K2_ApplySpecialLeftStatus();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_104994">();
	}
	static class UPyAbility_104994* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104994>();
	}
};
static_assert(alignof(UPyAbility_104994) == 0x000008, "Wrong alignment on UPyAbility_104994");
static_assert(sizeof(UPyAbility_104994) == 0x002D28, "Wrong size on UPyAbility_104994");

}

