#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_120_101561

#include "Basic.hpp"

#include "Marvel_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyBuffAbility_120_101561.PyBuffAbility_120_10156190.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyBuffAbility_120_10156190_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_120_10156190_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyBuffAbility_120_10156190_K2_OnEndAbility");
static_assert(sizeof(PyBuffAbility_120_10156190_K2_OnEndAbility) == 0x000001, "Wrong size on PyBuffAbility_120_10156190_K2_OnEndAbility");
static_assert(offsetof(PyBuffAbility_120_10156190_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyBuffAbility_120_10156190_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyBuffAbility_120_101561.PyBuffAbility_120_10156192.OnKillOther
// 0x0028 (0x0028 - 0x0000)
struct PyBuffAbility_120_10156192_OnKillOther final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ParamHandle;                                       // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_120_10156192_OnKillOther) == 0x000008, "Wrong alignment on PyBuffAbility_120_10156192_OnKillOther");
static_assert(sizeof(PyBuffAbility_120_10156192_OnKillOther) == 0x000028, "Wrong size on PyBuffAbility_120_10156192_OnKillOther");
static_assert(offsetof(PyBuffAbility_120_10156192_OnKillOther, InSourceAvatar) == 0x000000, "Member 'PyBuffAbility_120_10156192_OnKillOther::InSourceAvatar' has a wrong offset!");
static_assert(offsetof(PyBuffAbility_120_10156192_OnKillOther, InTargetAvatar) == 0x000008, "Member 'PyBuffAbility_120_10156192_OnKillOther::InTargetAvatar' has a wrong offset!");
static_assert(offsetof(PyBuffAbility_120_10156192_OnKillOther, ParamHandle) == 0x000010, "Member 'PyBuffAbility_120_10156192_OnKillOther::ParamHandle' has a wrong offset!");

// PythonFunction PyBuffAbility_120_101561.PyBuffAbility_120_10156192.MulticastRefreshAbilityDuration
// 0x0008 (0x0008 - 0x0000)
struct PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration final
{
public:
	float                                         NewDurationTotal;                                  // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NewDurationRemain;                                 // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration) == 0x000004, "Wrong alignment on PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration");
static_assert(sizeof(PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration) == 0x000008, "Wrong size on PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration");
static_assert(offsetof(PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration, NewDurationTotal) == 0x000000, "Member 'PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration::NewDurationTotal' has a wrong offset!");
static_assert(offsetof(PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration, NewDurationRemain) == 0x000004, "Member 'PyBuffAbility_120_10156192_MulticastRefreshAbilityDuration::NewDurationRemain' has a wrong offset!");

// PythonFunction PyBuffAbility_120_101561.PyBuffAbility_120_10156192.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyBuffAbility_120_10156192_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_120_10156192_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyBuffAbility_120_10156192_K2_OnEndAbility");
static_assert(sizeof(PyBuffAbility_120_10156192_K2_OnEndAbility) == 0x000001, "Wrong size on PyBuffAbility_120_10156192_K2_OnEndAbility");
static_assert(offsetof(PyBuffAbility_120_10156192_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyBuffAbility_120_10156192_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

