#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyCharacterOverlayManager

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyCharacterOverlayManager.PyCharacterOverlayManager
// 0x0010 (0x06F0 - 0x06E0)
#pragma pack(push, 0x1)
class alignas(0x10) APyCharacterOverlayManager : public AActor
{
public:
	uint8                                         Pad_6D8[0x8];                                      // 0x06D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         OverlayChangeTime;                                 // 0x06E0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsContainerRespawn;                                // 0x06E4(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCharacterOverlayManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCharacterOverlayManager")
	}
	static class APyCharacterOverlayManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCharacterOverlayManager>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_APyCharacterOverlayManager;

}

