#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyControlRuleComponent

#include "Basic.hpp"

#include "PyRuleComponent_classes.hpp"


namespace SDK
{

// PythonClass PyControlRuleComponent.PyControlRuleComponent
// 0x0010 (0x0118 - 0x0108)
class UPyControlRuleComponent final : public UPyRuleComponent
{
public:
	TSubclassOf<class AActor>                     ControlClass;                                      // 0x0108(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Control;                                           // 0x0110(0x0008)(Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ActivationNow(class APyControl* control);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyControlRuleComponent">();
	}
	static class UPyControlRuleComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyControlRuleComponent>();
	}
};
static_assert(alignof(UPyControlRuleComponent) == 0x000008, "Wrong alignment on UPyControlRuleComponent");
static_assert(sizeof(UPyControlRuleComponent) == 0x000118, "Wrong size on UPyControlRuleComponent");
static_assert(offsetof(UPyControlRuleComponent, ControlClass) == 0x000108, "Member 'UPyControlRuleComponent::ControlClass' has a wrong offset!");
static_assert(offsetof(UPyControlRuleComponent, Control) == 0x000110, "Member 'UPyControlRuleComponent::Control' has a wrong offset!");

}

