#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyHalloweenScopeCheckArea

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyHalloweenScopeCheckArea.PyHalloweenScopeCheckArea
// 0x0010 (0x06F0 - 0x06E0)
class APyHalloweenScopeCheckArea final : public AActor
{
public:
	uint8                                         Pad_6D8[0x8];                                      // 0x06D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class AActor* actor)> OnLocalPlayerEnterArea;                      // 0x06E0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyHalloweenScopeCheckArea">();
	}
	static class APyHalloweenScopeCheckArea* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyHalloweenScopeCheckArea>();
	}
};
static_assert(alignof(APyHalloweenScopeCheckArea) == 0x000010, "Wrong alignment on APyHalloweenScopeCheckArea");
static_assert(sizeof(APyHalloweenScopeCheckArea) == 0x0006F0, "Wrong size on APyHalloweenScopeCheckArea");
static_assert(offsetof(APyHalloweenScopeCheckArea, OnLocalPlayerEnterArea) == 0x0006E0, "Member 'APyHalloweenScopeCheckArea::OnLocalPlayerEnterArea' has a wrong offset!");

}

