#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyKeyWidgetManager

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyKeyWidgetManager.PyKeyWidgetManager
// 0x0000 (0x0038 - 0x0038)
class UPyKeyWidgetManager final : public UMarvelWorldSubsystem
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyKeyWidgetManager">();
	}
	static class UPyKeyWidgetManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyKeyWidgetManager>();
	}
};
static_assert(alignof(UPyKeyWidgetManager) == 0x000008, "Wrong alignment on UPyKeyWidgetManager");
static_assert(sizeof(UPyKeyWidgetManager) == 0x000038, "Wrong size on UPyKeyWidgetManager");

}

