#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelSingleDeathMatchAudioComponent

#include "Basic.hpp"

#include "PyLevelDeathMatchAudioComponent_classes.hpp"
#include "MarvelLevel_structs.hpp"
#include "PyAudioItemConfig_classes.hpp"


namespace SDK
{

// PythonClass PyLevelSingleDeathMatchAudioComponent.PyLevelSingleDeathMatchAudioComponent
// 0x0000 (0x0120 - 0x0120)
class UPyLevelSingleDeathMatchAudioComponent final : public UPyLevelDeathMatchAudioComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelSingleDeathMatchAudioComponent">();
	}
	static class UPyLevelSingleDeathMatchAudioComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyLevelSingleDeathMatchAudioComponent>();
	}
};
static_assert(alignof(UPyLevelSingleDeathMatchAudioComponent) == 0x000008, "Wrong alignment on UPyLevelSingleDeathMatchAudioComponent");
static_assert(sizeof(UPyLevelSingleDeathMatchAudioComponent) == 0x000120, "Wrong size on UPyLevelSingleDeathMatchAudioComponent");

// PythonClass PyLevelSingleDeathMatchAudioComponent.PyLevelSingleDeathMatchAudioItem
// 0x0140 (0x0218 - 0x00D8)
class UPyLevelSingleDeathMatchAudioItem final : public UPyLevelModeCommonAudioItem
{
public:
	class FString                                 SwitchAudioNumberKey;                              // 0x00D8(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             Respawn;                                           // 0x00E8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             WinScoreCheck;                                     // 0x00F8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             AddScore;                                          // 0x0108(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SubScore;                                          // 0x0118(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SelfScoreWin1;                                     // 0x0128(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SelfScoreWin2;                                     // 0x0138(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SelfScoreWin3;                                     // 0x0148(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SelfScoreWin4;                                     // 0x0158(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SelfScoreWin5;                                     // 0x0168(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             SelfScoreWin6;                                     // 0x0178(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyScoreWin1;                                    // 0x0188(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyScoreWin2;                                    // 0x0198(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyScoreWin3;                                    // 0x01A8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyScoreWin4;                                    // 0x01B8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyScoreWin5;                                    // 0x01C8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyScoreWin6;                                    // 0x01D8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             FirstWinner;                                       // 0x01E8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             GainAdvantage;                                     // 0x01F8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             LostAdvantage;                                     // 0x0208(0x0010)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelSingleDeathMatchAudioItem">();
	}
	static class UPyLevelSingleDeathMatchAudioItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyLevelSingleDeathMatchAudioItem>();
	}
};
static_assert(alignof(UPyLevelSingleDeathMatchAudioItem) == 0x000008, "Wrong alignment on UPyLevelSingleDeathMatchAudioItem");
static_assert(sizeof(UPyLevelSingleDeathMatchAudioItem) == 0x000218, "Wrong size on UPyLevelSingleDeathMatchAudioItem");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SwitchAudioNumberKey) == 0x0000D8, "Member 'UPyLevelSingleDeathMatchAudioItem::SwitchAudioNumberKey' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, Respawn) == 0x0000E8, "Member 'UPyLevelSingleDeathMatchAudioItem::Respawn' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, WinScoreCheck) == 0x0000F8, "Member 'UPyLevelSingleDeathMatchAudioItem::WinScoreCheck' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, AddScore) == 0x000108, "Member 'UPyLevelSingleDeathMatchAudioItem::AddScore' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SubScore) == 0x000118, "Member 'UPyLevelSingleDeathMatchAudioItem::SubScore' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SelfScoreWin1) == 0x000128, "Member 'UPyLevelSingleDeathMatchAudioItem::SelfScoreWin1' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SelfScoreWin2) == 0x000138, "Member 'UPyLevelSingleDeathMatchAudioItem::SelfScoreWin2' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SelfScoreWin3) == 0x000148, "Member 'UPyLevelSingleDeathMatchAudioItem::SelfScoreWin3' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SelfScoreWin4) == 0x000158, "Member 'UPyLevelSingleDeathMatchAudioItem::SelfScoreWin4' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SelfScoreWin5) == 0x000168, "Member 'UPyLevelSingleDeathMatchAudioItem::SelfScoreWin5' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, SelfScoreWin6) == 0x000178, "Member 'UPyLevelSingleDeathMatchAudioItem::SelfScoreWin6' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, EnemyScoreWin1) == 0x000188, "Member 'UPyLevelSingleDeathMatchAudioItem::EnemyScoreWin1' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, EnemyScoreWin2) == 0x000198, "Member 'UPyLevelSingleDeathMatchAudioItem::EnemyScoreWin2' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, EnemyScoreWin3) == 0x0001A8, "Member 'UPyLevelSingleDeathMatchAudioItem::EnemyScoreWin3' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, EnemyScoreWin4) == 0x0001B8, "Member 'UPyLevelSingleDeathMatchAudioItem::EnemyScoreWin4' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, EnemyScoreWin5) == 0x0001C8, "Member 'UPyLevelSingleDeathMatchAudioItem::EnemyScoreWin5' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, EnemyScoreWin6) == 0x0001D8, "Member 'UPyLevelSingleDeathMatchAudioItem::EnemyScoreWin6' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, FirstWinner) == 0x0001E8, "Member 'UPyLevelSingleDeathMatchAudioItem::FirstWinner' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, GainAdvantage) == 0x0001F8, "Member 'UPyLevelSingleDeathMatchAudioItem::GainAdvantage' has a wrong offset!");
static_assert(offsetof(UPyLevelSingleDeathMatchAudioItem, LostAdvantage) == 0x000208, "Member 'UPyLevelSingleDeathMatchAudioItem::LostAdvantage' has a wrong offset!");

}

