#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelSummoned_20000006

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "MarvelLevel_classes.hpp"
#include "PyLevelOverlapHandlerComponent_classes.hpp"


namespace SDK
{

// PythonClass PyLevelSummoned_20000006.PyLevelSummoned_20000006
// 0x0040 (0x0BB0 - 0x0B70)
class APyLevelSummoned_20000006 : public AMarvelLevelSummonedBase
{
public:
	uint8                                         Pad_B68[0x8];                                      // 0x0B68(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          DeathAudio;                                        // 0x0B70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpawnGapTime;                                      // 0x0B78(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B7C[0x4];                                      // 0x0B7C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                GrowthScale;                                       // 0x0B80(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GrowthTime;                                        // 0x0B98(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         VanishTime;                                        // 0x0B9C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SubSummonedID;                                     // 0x0BA0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DefaultActive;                                     // 0x0BA4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_BA5[0x3];                                      // 0x0BA5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GrowthPercent;                                     // 0x0BA8(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         State;                                             // 0x0BAC(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void ReceiveBeginPlay();
	void OnLevelStart();
	void ReceiveTick(float DeltaSeconds);
	void OnDeath(class AController* InSource, class AActor* InSourceAvatar, const struct FAttributeModifierHandle& ParameterHandle);
	void K2_SetState(int32 NewState);
	void OnRep_State();
	void OnRep_GrowthPercent();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelSummoned_20000006">();
	}
	static class APyLevelSummoned_20000006* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLevelSummoned_20000006>();
	}
};
static_assert(alignof(APyLevelSummoned_20000006) == 0x000010, "Wrong alignment on APyLevelSummoned_20000006");
static_assert(sizeof(APyLevelSummoned_20000006) == 0x000BB0, "Wrong size on APyLevelSummoned_20000006");
static_assert(offsetof(APyLevelSummoned_20000006, DeathAudio) == 0x000B70, "Member 'APyLevelSummoned_20000006::DeathAudio' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, SpawnGapTime) == 0x000B78, "Member 'APyLevelSummoned_20000006::SpawnGapTime' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, GrowthScale) == 0x000B80, "Member 'APyLevelSummoned_20000006::GrowthScale' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, GrowthTime) == 0x000B98, "Member 'APyLevelSummoned_20000006::GrowthTime' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, VanishTime) == 0x000B9C, "Member 'APyLevelSummoned_20000006::VanishTime' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, SubSummonedID) == 0x000BA0, "Member 'APyLevelSummoned_20000006::SubSummonedID' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, DefaultActive) == 0x000BA4, "Member 'APyLevelSummoned_20000006::DefaultActive' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, GrowthPercent) == 0x000BA8, "Member 'APyLevelSummoned_20000006::GrowthPercent' has a wrong offset!");
static_assert(offsetof(APyLevelSummoned_20000006, State) == 0x000BAC, "Member 'APyLevelSummoned_20000006::State' has a wrong offset!");

// PythonClass PyLevelSummoned_20000006.PyOverlapHandlerComponent_ManaEgg
// 0x0008 (0x0D70 - 0x0D68)
class UPyOverlapHandlerComponent_ManaEgg final : public UPyLevelOverlapHandlerComponent
{
public:
	float                                         UltimateChargePercent;                             // 0x0D68(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ApplyEffectOnActorOverlap(class AActor* InActor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyOverlapHandlerComponent_ManaEgg">();
	}
	static class UPyOverlapHandlerComponent_ManaEgg* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyOverlapHandlerComponent_ManaEgg>();
	}
};
static_assert(alignof(UPyOverlapHandlerComponent_ManaEgg) == 0x000008, "Wrong alignment on UPyOverlapHandlerComponent_ManaEgg");
static_assert(sizeof(UPyOverlapHandlerComponent_ManaEgg) == 0x000D70, "Wrong size on UPyOverlapHandlerComponent_ManaEgg");
static_assert(offsetof(UPyOverlapHandlerComponent_ManaEgg, UltimateChargePercent) == 0x000D68, "Member 'UPyOverlapHandlerComponent_ManaEgg::UltimateChargePercent' has a wrong offset!");

// PythonClass PyLevelSummoned_20000006.PySummonedComp_EggBase
// 0x0000 (0x0DB0 - 0x0DB0)
class UPySummonedComp_EggBase final : public ULevelSummonedComponent
{
public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySummonedComp_EggBase">();
	}
	static class UPySummonedComp_EggBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySummonedComp_EggBase>();
	}
};
static_assert(alignof(UPySummonedComp_EggBase) == 0x000008, "Wrong alignment on UPySummonedComp_EggBase");
static_assert(sizeof(UPySummonedComp_EggBase) == 0x000DB0, "Wrong size on UPySummonedComp_EggBase");

// PythonClass PyLevelSummoned_20000006.BuffCue_20020401
// 0x0060 (0x16A0 - 0x1640)
class ABuffCue_20020401 final : public AMarvelCueNotify_Buff
{
public:
	uint8                                         Pad_1638[0x8];                                     // 0x1638(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 OpenParemName;                                     // 0x1640(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ColorParamName;                                    // 0x1650(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 FractionParamName;                                 // 0x1660(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                FresnelColor;                                      // 0x1670(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                FresnelParam;                                      // 0x1688(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BuffCue_20020401">();
	}
	static class ABuffCue_20020401* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuffCue_20020401>();
	}
};
static_assert(alignof(ABuffCue_20020401) == 0x000010, "Wrong alignment on ABuffCue_20020401");
static_assert(sizeof(ABuffCue_20020401) == 0x0016A0, "Wrong size on ABuffCue_20020401");
static_assert(offsetof(ABuffCue_20020401, OpenParemName) == 0x001640, "Member 'ABuffCue_20020401::OpenParemName' has a wrong offset!");
static_assert(offsetof(ABuffCue_20020401, ColorParamName) == 0x001650, "Member 'ABuffCue_20020401::ColorParamName' has a wrong offset!");
static_assert(offsetof(ABuffCue_20020401, FractionParamName) == 0x001660, "Member 'ABuffCue_20020401::FractionParamName' has a wrong offset!");
static_assert(offsetof(ABuffCue_20020401, FresnelColor) == 0x001670, "Member 'ABuffCue_20020401::FresnelColor' has a wrong offset!");
static_assert(offsetof(ABuffCue_20020401, FresnelParam) == 0x001688, "Member 'ABuffCue_20020401::FresnelParam' has a wrong offset!");

// PythonClass PyLevelSummoned_20000006.PyCue_Summoner_Loop_20000006
// 0x0000 (0x1200 - 0x1200)
class APyCue_Summoner_Loop_20000006 final : public AMarvelCueNotify_Summoned
{
public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Summoner_Loop_20000006">();
	}
	static class APyCue_Summoner_Loop_20000006* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Summoner_Loop_20000006>();
	}
};
static_assert(alignof(APyCue_Summoner_Loop_20000006) == 0x000010, "Wrong alignment on APyCue_Summoner_Loop_20000006");
static_assert(sizeof(APyCue_Summoner_Loop_20000006) == 0x001200, "Wrong size on APyCue_Summoner_Loop_20000006");

}

