#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNoviceHealPracticeComputer

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "PyNoviceComputer_classes.hpp"


namespace SDK
{

// PythonClass PyNoviceHealPracticeComputer.PyNoviceHealPracticeComputer
// 0x00D0 (0x0860 - 0x0790)
class APyNoviceHealPracticeComputer final : public APyNoviceComputer
{
public:
	TArray<class APyAINoviceSpawnActor*>          AISpawnActorList;                                  // 0x0790(0x0010)(Edit, DisableEditOnTemplate, NativeAccessSpecifierPublic)
	int32                                         PrepareTime;                                       // 0x07A0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PracticeTime;                                      // 0x07A4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUIActionData                          FirstPressActionTips;                              // 0x07A8(0x0058)(Edit, NativeAccessSpecifierPublic)
	class FText                                   TrainingText;                                      // 0x0800(0x0018)(Edit, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPracticeFirstStart;                              // 0x0818(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPracticeTimeOut;                                 // 0x0828(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPracticeRestart;                                 // 0x0838(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPracticeExit;                                    // 0x0848(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyNoviceHealPracticeComputer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyNoviceHealPracticeComputer")
	}
	static class APyNoviceHealPracticeComputer* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyNoviceHealPracticeComputer>();
	}
};
DUMPER7_ASSERTS_APyNoviceHealPracticeComputer;

}

