#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNoviceComputer

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyNoviceComputer.PyNoviceComputer
// 0x00B0 (0x0790 - 0x06E0)
class APyNoviceComputer : public AMarvelLevelActorBase
{
public:
	uint8                                         Pad_6D8[0x8];                                      // 0x06D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUIActionData                          HoldActionTips;                                    // 0x06E0(0x0058)(Edit, NativeAccessSpecifierPublic)
	struct FUIActionData                          PressActionTips;                                   // 0x0738(0x0058)(Edit, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyNoviceComputer">();
	}
	static class APyNoviceComputer* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyNoviceComputer>();
	}
};
static_assert(alignof(APyNoviceComputer) == 0x000010, "Wrong alignment on APyNoviceComputer");
static_assert(sizeof(APyNoviceComputer) == 0x000790, "Wrong size on APyNoviceComputer");
static_assert(offsetof(APyNoviceComputer, HoldActionTips) == 0x0006E0, "Member 'APyNoviceComputer::HoldActionTips' has a wrong offset!");
static_assert(offsetof(APyNoviceComputer, PressActionTips) == 0x000738, "Member 'APyNoviceComputer::PressActionTips' has a wrong offset!");

}

