#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_PopupAd_Activity150

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_PopupAd_Activity150.PyWidget_PopupAd_Activity150
// 0x0000 (0x05C0 - 0x05C0)
class UPyWidget_PopupAd_Activity150 final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_PopupAd_Activity150">();
	}
	static class UPyWidget_PopupAd_Activity150* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_PopupAd_Activity150>();
	}
};
static_assert(alignof(UPyWidget_PopupAd_Activity150) == 0x000008, "Wrong alignment on UPyWidget_PopupAd_Activity150");
static_assert(sizeof(UPyWidget_PopupAd_Activity150) == 0x0005C0, "Wrong size on UPyWidget_PopupAd_Activity150");

}

