#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_StoreLottery_ThrowDart

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_StoreLottery_ThrowDart.PyWidget_StoreLottery_ThrowDart
// 0x0010 (0x05D8 - 0x05C8)
class UPyWidget_StoreLottery_ThrowDart final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5C2[0x6];                                      // 0x05C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnClicked;                                         // 0x05C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void OnCascadingVisibleChanged(bool bNewVisible);
	void MarvelSetVisible(bool bTmpVisible);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_StoreLottery_ThrowDart")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_StoreLottery_ThrowDart")
	}
	static class UPyWidget_StoreLottery_ThrowDart* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_StoreLottery_ThrowDart>();
	}
};
DUMPER7_ASSERTS_UPyWidget_StoreLottery_ThrowDart;

}

