#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Halloween_Card_Base

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Halloween_Card_Base.PyWidget_Halloween_Card_Base.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Halloween_Card_Base_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_Halloween_Card_Base_PreConstruct) == 0x000001, "Wrong alignment on PyWidget_Halloween_Card_Base_PreConstruct");
static_assert(sizeof(PyWidget_Halloween_Card_Base_PreConstruct) == 0x000001, "Wrong size on PyWidget_Halloween_Card_Base_PreConstruct");
static_assert(offsetof(PyWidget_Halloween_Card_Base_PreConstruct, IsDesignTime) == 0x000000, "Member 'PyWidget_Halloween_Card_Base_PreConstruct::IsDesignTime' has a wrong offset!");

// PythonFunction PyWidget_Halloween_Card_Base.PyWidget_Halloween_Card_Base.OnCascadingVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged) == 0x000001, "Wrong alignment on PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged");
static_assert(sizeof(PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged) == 0x000001, "Wrong size on PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged");
static_assert(offsetof(PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged, bNewVisible) == 0x000000, "Member 'PyWidget_Halloween_Card_Base_OnCascadingVisibleChanged::bNewVisible' has a wrong offset!");

// PythonFunction PyWidget_Halloween_Card_Base.PyWidget_Halloween_Card_Base.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_Halloween_Card_Base_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_Halloween_Card_Base_OnAnimationFinished) == 0x000008, "Wrong alignment on PyWidget_Halloween_Card_Base_OnAnimationFinished");
static_assert(sizeof(PyWidget_Halloween_Card_Base_OnAnimationFinished) == 0x000008, "Wrong size on PyWidget_Halloween_Card_Base_OnAnimationFinished");
static_assert(offsetof(PyWidget_Halloween_Card_Base_OnAnimationFinished, Animation) == 0x000000, "Member 'PyWidget_Halloween_Card_Base_OnAnimationFinished::Animation' has a wrong offset!");

}

