#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Halloween_LotteryPanel

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Halloween_LotteryPanel.PyWidget_Halloween_LotteryCardData
// 0x0000 (0x0030 - 0x0030)
class UPyWidget_Halloween_LotteryCardData final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Halloween_LotteryCardData">();
	}
	static class UPyWidget_Halloween_LotteryCardData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Halloween_LotteryCardData>();
	}
};
static_assert(alignof(UPyWidget_Halloween_LotteryCardData) == 0x000008, "Wrong alignment on UPyWidget_Halloween_LotteryCardData");
static_assert(sizeof(UPyWidget_Halloween_LotteryCardData) == 0x000030, "Wrong size on UPyWidget_Halloween_LotteryCardData");

// PythonClass PyWidget_Halloween_LotteryPanel.PyWidget_Halloween_LotteryPanel
// 0x0068 (0x0660 - 0x05F8)
class UPyWidget_Halloween_LotteryPanel final : public UPyWidget_ModuleMainPanel
{
public:
	TArray<struct FGuideTipsStyle>                SkipStyle;                                         // 0x05F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                BackStyle;                                         // 0x0608(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          StartAudio;                                        // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          ChooseAudio;                                       // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          ResultAudio;                                       // 0x0628(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            Curve;                                             // 0x0630(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BaseSpeed;                                         // 0x0638(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RollTime;                                          // 0x063C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ChooseDelayTime;                                   // 0x0640(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ChooseTime;                                        // 0x0644(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EndDelayTime;                                      // 0x0648(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AnimFrequency;                                     // 0x064C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ArrowOffset;                                       // 0x0650(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ArrowRandomOffset;                                 // 0x0654(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AutoExitTime;                                      // 0x0658(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Halloween_LotteryPanel">();
	}
	static class UPyWidget_Halloween_LotteryPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Halloween_LotteryPanel>();
	}
};
static_assert(alignof(UPyWidget_Halloween_LotteryPanel) == 0x000008, "Wrong alignment on UPyWidget_Halloween_LotteryPanel");
static_assert(sizeof(UPyWidget_Halloween_LotteryPanel) == 0x000660, "Wrong size on UPyWidget_Halloween_LotteryPanel");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, SkipStyle) == 0x0005F8, "Member 'UPyWidget_Halloween_LotteryPanel::SkipStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, BackStyle) == 0x000608, "Member 'UPyWidget_Halloween_LotteryPanel::BackStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, StartAudio) == 0x000618, "Member 'UPyWidget_Halloween_LotteryPanel::StartAudio' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, ChooseAudio) == 0x000620, "Member 'UPyWidget_Halloween_LotteryPanel::ChooseAudio' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, ResultAudio) == 0x000628, "Member 'UPyWidget_Halloween_LotteryPanel::ResultAudio' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, Curve) == 0x000630, "Member 'UPyWidget_Halloween_LotteryPanel::Curve' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, BaseSpeed) == 0x000638, "Member 'UPyWidget_Halloween_LotteryPanel::BaseSpeed' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, RollTime) == 0x00063C, "Member 'UPyWidget_Halloween_LotteryPanel::RollTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, ChooseDelayTime) == 0x000640, "Member 'UPyWidget_Halloween_LotteryPanel::ChooseDelayTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, ChooseTime) == 0x000644, "Member 'UPyWidget_Halloween_LotteryPanel::ChooseTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, EndDelayTime) == 0x000648, "Member 'UPyWidget_Halloween_LotteryPanel::EndDelayTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, AnimFrequency) == 0x00064C, "Member 'UPyWidget_Halloween_LotteryPanel::AnimFrequency' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, ArrowOffset) == 0x000650, "Member 'UPyWidget_Halloween_LotteryPanel::ArrowOffset' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, ArrowRandomOffset) == 0x000654, "Member 'UPyWidget_Halloween_LotteryPanel::ArrowRandomOffset' has a wrong offset!");
static_assert(offsetof(UPyWidget_Halloween_LotteryPanel, AutoExitTime) == 0x000658, "Member 'UPyWidget_Halloween_LotteryPanel::AutoExitTime' has a wrong offset!");

}

