#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BattleChessRulePanel

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_BattleChessRulePanel.PyWidget_BattleChessRulePanel
// 0x0000 (0x05F8 - 0x05F8)
class UPyWidget_BattleChessRulePanel final : public UPyWidget_ModuleMainPanel
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BattleChessRulePanel">();
	}
	static class UPyWidget_BattleChessRulePanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BattleChessRulePanel>();
	}
};
static_assert(alignof(UPyWidget_BattleChessRulePanel) == 0x000008, "Wrong alignment on UPyWidget_BattleChessRulePanel");
static_assert(sizeof(UPyWidget_BattleChessRulePanel) == 0x0005F8, "Wrong size on UPyWidget_BattleChessRulePanel");

// PythonClass PyWidget_BattleChessRulePanel.PyWidget_BattleChessRuleItem
// 0x0030 (0x05F0 - 0x05C0)
class UPyWidget_BattleChessRuleItem final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5BA[0x6];                                      // 0x05BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Title;                                             // 0x05C0(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   Desc;                                              // 0x05D8(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BattleChessRuleItem">();
	}
	static class UPyWidget_BattleChessRuleItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BattleChessRuleItem>();
	}
};
static_assert(alignof(UPyWidget_BattleChessRuleItem) == 0x000008, "Wrong alignment on UPyWidget_BattleChessRuleItem");
static_assert(sizeof(UPyWidget_BattleChessRuleItem) == 0x0005F0, "Wrong size on UPyWidget_BattleChessRuleItem");
static_assert(offsetof(UPyWidget_BattleChessRuleItem, Title) == 0x0005C0, "Member 'UPyWidget_BattleChessRuleItem::Title' has a wrong offset!");
static_assert(offsetof(UPyWidget_BattleChessRuleItem, Desc) == 0x0005D8, "Member 'UPyWidget_BattleChessRuleItem::Desc' has a wrong offset!");

}

