#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity143_Purchase

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Activity143_Purchase.PyWidget_Activity143_Purchase
// 0x0108 (0x0708 - 0x0600)
class UPyWidget_Activity143_Purchase final : public UPyWidget_ModuleMainPanel
{
public:
	struct FSlateColor                            RedSlateColor;                                     // 0x0600(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FLinearColor                           RedLinearColor;                                    // 0x0614(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            WhiteSlateColor;                                   // 0x0624(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FLinearColor                           WhiteLinearColor;                                  // 0x0638(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ConfirmKeyPromptVisible;                           // 0x0648(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_649[0x7];                                      // 0x0649(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUIActionData                          ConfirmHotKey;                                     // 0x0650(0x0058)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          CancelKeyPromptVisible;                            // 0x06A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6A9[0x7];                                      // 0x06A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUIActionData                          CancelHotKey;                                      // 0x06B0(0x0058)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnCascadingVisibleChanged(bool bNewVisible);
	class UButton* on_try_scroll_when_next_focusable_child_change(int32 ChildIndex, int32 FocusedChildDirection, int32 NumItemsLine);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Activity143_Purchase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Activity143_Purchase")
	}
	static class UPyWidget_Activity143_Purchase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity143_Purchase>();
	}
};
DUMPER7_ASSERTS_UPyWidget_Activity143_Purchase;

}

