#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_HomeEntrance_Activity_Item_134

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "PyWidget_HomeEntrance_Activity_Item_Base_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_HomeEntrance_Activity_Item_134.PyWidget_HomeEntrance_Activity_134
// 0x0048 (0x0608 - 0x05C0)
class UPyWidget_HomeEntrance_Activity_134 final : public UPyWidget_HomeEntrance_Activity_Item_Widget_Base
{
public:
	uint8                                         Pad_5BA[0x2];                                      // 0x05BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            RedSlateColor;                                     // 0x05BC(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FLinearColor                           RedLinearColor;                                    // 0x05D0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            WhiteSlateColor;                                   // 0x05E0(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FLinearColor                           WhiteLinearColor;                                  // 0x05F4(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_HomeEntrance_Activity_134">();
	}
	static class UPyWidget_HomeEntrance_Activity_134* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_HomeEntrance_Activity_134>();
	}
};
static_assert(alignof(UPyWidget_HomeEntrance_Activity_134) == 0x000008, "Wrong alignment on UPyWidget_HomeEntrance_Activity_134");
static_assert(sizeof(UPyWidget_HomeEntrance_Activity_134) == 0x000608, "Wrong size on UPyWidget_HomeEntrance_Activity_134");
static_assert(offsetof(UPyWidget_HomeEntrance_Activity_134, RedSlateColor) == 0x0005BC, "Member 'UPyWidget_HomeEntrance_Activity_134::RedSlateColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_HomeEntrance_Activity_134, RedLinearColor) == 0x0005D0, "Member 'UPyWidget_HomeEntrance_Activity_134::RedLinearColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_HomeEntrance_Activity_134, WhiteSlateColor) == 0x0005E0, "Member 'UPyWidget_HomeEntrance_Activity_134::WhiteSlateColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_HomeEntrance_Activity_134, WhiteLinearColor) == 0x0005F4, "Member 'UPyWidget_HomeEntrance_Activity_134::WhiteLinearColor' has a wrong offset!");

}

