#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_CareerHonorItem

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_CareerHonorItem.PyWidget_CareerHonorItem
// 0x0018 (0x05E0 - 0x05C8)
class UPyWidget_CareerHonorItem final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5C2[0x6];                                      // 0x05C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             EmptyBackground;                                   // 0x05C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnClicked;                                         // 0x05D0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_CareerHonorItem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_CareerHonorItem")
	}
	static class UPyWidget_CareerHonorItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CareerHonorItem>();
	}
};
DUMPER7_ASSERTS_UPyWidget_CareerHonorItem;

}

