#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Traning_ScoreBoard

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"
#include "UMG_classes.hpp"
#include "Engine_structs.hpp"
#include "Marvel_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Traning_ScoreBoard.WC_Training_Monitor
// 0x0010 (0x0A10 - 0x0A00)
class UWC_Training_Monitor : public UWidgetComponent
{
public:
	class UAkAudioEvent*                          SwitchAudioEvent;                                  // 0x0A00(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("WC_Training_Monitor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WC_Training_Monitor")
	}
	static class UWC_Training_Monitor* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWC_Training_Monitor>();
	}
};
DUMPER7_ASSERTS_UWC_Training_Monitor;

// PythonClass PyWidget_Traning_ScoreBoard.PyWidget_Training_Scoreboard
// 0x0010 (0x0880 - 0x0870)
#pragma pack(push, 0x1)
class alignas(0x10) UPyWidget_Training_Scoreboard : public UMarvel3DWidget
{
public:
	uint8                                         Pad_868[0x8];                                      // 0x0868(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ResetTime;                                         // 0x0870(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          HideWhenLeave;                                     // 0x0874(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Training_Scoreboard")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Training_Scoreboard")
	}
	static class UPyWidget_Training_Scoreboard* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Training_Scoreboard>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_UPyWidget_Training_Scoreboard;

// PythonClass PyWidget_Traning_ScoreBoard.PyWidget_Training_Scoreboard_Unit
// 0x0028 (0x05F0 - 0x05C8)
class UPyWidget_Training_Scoreboard_Unit : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5C2[0x2];                                      // 0x05C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Icon_Index;                                        // 0x05C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSlateBrush>                    Icon_list;                                         // 0x05C8(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   Title;                                             // 0x05D8(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Training_Scoreboard_Unit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Training_Scoreboard_Unit")
	}
	static class UPyWidget_Training_Scoreboard_Unit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Training_Scoreboard_Unit>();
	}
};
DUMPER7_ASSERTS_UPyWidget_Training_Scoreboard_Unit;

}

