#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_CareerUsedHeroRecordDetails_HeroDataItem

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_CareerUsedHeroRecordDetails_HeroDataItem.PyWidget_CareerUsedHeroRecordDetails_HeroDataItem
// 0x0000 (0x05C0 - 0x05C0)
class UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_CareerUsedHeroRecordDetails_HeroDataItem">();
	}
	static class UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem>();
	}
};
static_assert(alignof(UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem) == 0x000008, "Wrong alignment on UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem");
static_assert(sizeof(UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem) == 0x0005C0, "Wrong size on UPyWidget_CareerUsedHeroRecordDetails_HeroDataItem");

}

