#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Renderer

#include "Basic.hpp"

#include "Renderer_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class Renderer.SparseVolumeTextureViewerComponent
// 0x0040 (0x0800 - 0x07C0)
class USparseVolumeTextureViewerComponent final : public UPrimitiveComponent
{
public:
	class USparseVolumeTexture*                   SparseVolumeTexturePreview;                        // 0x07B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bAnimate : 1;                                      // 0x07C0(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bReversePlayback : 1;                              // 0x07C0(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bBlockingStreamingRequests : 1;                    // 0x07C0(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_7C1[0x3];                                      // 0x07C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AnimationFrame;                                    // 0x07C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FrameRate;                                         // 0x07C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AnimationTime;                                     // 0x07CC(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESparseVolumeTexturePreviewAttribute          PreviewAttribute;                                  // 0x07D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7D1[0x3];                                      // 0x07D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MipLevel;                                          // 0x07D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Extinction;                                        // 0x07D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7DC[0x24];                                     // 0x07DC(0x0024)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SparseVolumeTextureViewerComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SparseVolumeTextureViewerComponent")
	}
	static class USparseVolumeTextureViewerComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<USparseVolumeTextureViewerComponent>();
	}
};
DUMPER7_ASSERTS_USparseVolumeTextureViewerComponent;

// Class Renderer.SparseVolumeTextureViewer
// 0x0000 (0x06E0 - 0x06E0)
class ASparseVolumeTextureViewer final : public AInfo
{
public:
	class USparseVolumeTextureViewerComponent*    SparseVolumeTextureViewerComponent;                // 0x06D8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SparseVolumeTextureViewer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SparseVolumeTextureViewer")
	}
	static class ASparseVolumeTextureViewer* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASparseVolumeTextureViewer>();
	}
};
DUMPER7_ASSERTS_ASparseVolumeTextureViewer;

}

