#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReplaySpectating_Score

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ReplaySpectating_Score.WBP_ReplaySpectating_Score_C
// 0x0010 (0x03C8 - 0x03B8)
class UWBP_ReplaySpectating_Score_C final : public UUserWidget
{
public:
	class UMarvelImage*                           Img_Score;                                         // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Score;                                     // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ReplaySpectating_Score_C">();
	}
	static class UWBP_ReplaySpectating_Score_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ReplaySpectating_Score_C>();
	}
};
static_assert(alignof(UWBP_ReplaySpectating_Score_C) == 0x000008, "Wrong alignment on UWBP_ReplaySpectating_Score_C");
static_assert(sizeof(UWBP_ReplaySpectating_Score_C) == 0x0003C8, "Wrong size on UWBP_ReplaySpectating_Score_C");
static_assert(offsetof(UWBP_ReplaySpectating_Score_C, Img_Score) == 0x0003B8, "Member 'UWBP_ReplaySpectating_Score_C::Img_Score' has a wrong offset!");
static_assert(offsetof(UWBP_ReplaySpectating_Score_C, Overlay_Score) == 0x0003C0, "Member 'UWBP_ReplaySpectating_Score_C::Overlay_Score' has a wrong offset!");

}

