#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Settimg_CustomBlockedWords_Item

#include "Basic.hpp"

#include "PyWidget_Setting_CustomBlockedWords_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Settimg_CustomBlockedWords_Item.WBP_Settimg_CustomBlockedWords_Item_C
// 0x0008 (0x05C8 - 0x05C0)
class UWBP_Settimg_CustomBlockedWords_Item_C final : public UPyWidget_Setting_CustomBlockedWords_Item
{
public:
	class UMarvelTextBlock*                       Text_BlockedWords;                                 // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Settimg_CustomBlockedWords_Item_C">();
	}
	static class UWBP_Settimg_CustomBlockedWords_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Settimg_CustomBlockedWords_Item_C>();
	}
};
static_assert(alignof(UWBP_Settimg_CustomBlockedWords_Item_C) == 0x000008, "Wrong alignment on UWBP_Settimg_CustomBlockedWords_Item_C");
static_assert(sizeof(UWBP_Settimg_CustomBlockedWords_Item_C) == 0x0005C8, "Wrong size on UWBP_Settimg_CustomBlockedWords_Item_C");
static_assert(offsetof(UWBP_Settimg_CustomBlockedWords_Item_C, Text_BlockedWords) == 0x0005C0, "Member 'UWBP_Settimg_CustomBlockedWords_Item_C::Text_BlockedWords' has a wrong offset!");

}

