#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Mission_BattleTips

#include "Basic.hpp"

#include "PyWidget_BattleMissionTips_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Mission_BattleTips.WBP_Mission_BattleTips_C
// 0x0028 (0x05F0 - 0x05C8)
class UWBP_Mission_BattleTips_C final : public UPyWidget_BattleMissionTips
{
public:
	class UWidgetAnimation*                       Anim_Hide;                                         // 0x05C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Show;                                         // 0x05D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Img_Finish;                                        // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_MissionIcon;                                   // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_Num;                                          // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Mission_BattleTips_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Mission_BattleTips_C")
	}
	static class UWBP_Mission_BattleTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Mission_BattleTips_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Mission_BattleTips_C;

}

