#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AbilityHUDCom_EnergyRight

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AbilityHUDCom_EnergyRight.WBP_AbilityHUDCom_EnergyRight_C
// 0x0038 (0x05D8 - 0x05A0)
class UWBP_AbilityHUDCom_EnergyRight_C final : public UWidget_AbilityEnergy
{
public:
	class UWidgetAnimation*                       Anim_Flash_Once;                                   // 0x05A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Flash_Loop;                                   // 0x05A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Progress;                                     // 0x05B0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_Root;                                       // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Frame;                                         // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_ProgBg;                                        // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Mat_Prog;                                          // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_AbilityHUDCom_EnergyRight_C">();
	}
	static class UWBP_AbilityHUDCom_EnergyRight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AbilityHUDCom_EnergyRight_C>();
	}
};
static_assert(alignof(UWBP_AbilityHUDCom_EnergyRight_C) == 0x000008, "Wrong alignment on UWBP_AbilityHUDCom_EnergyRight_C");
static_assert(sizeof(UWBP_AbilityHUDCom_EnergyRight_C) == 0x0005D8, "Wrong size on UWBP_AbilityHUDCom_EnergyRight_C");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Anim_Flash_Once) == 0x0005A0, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Anim_Flash_Once' has a wrong offset!");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Anim_Flash_Loop) == 0x0005A8, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Anim_Flash_Loop' has a wrong offset!");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Anim_Progress) == 0x0005B0, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Anim_Progress' has a wrong offset!");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Canvas_Root) == 0x0005B8, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Canvas_Root' has a wrong offset!");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Img_Frame) == 0x0005C0, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Img_Frame' has a wrong offset!");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Img_ProgBg) == 0x0005C8, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Img_ProgBg' has a wrong offset!");
static_assert(offsetof(UWBP_AbilityHUDCom_EnergyRight_C, Mat_Prog) == 0x0005D0, "Member 'UWBP_AbilityHUDCom_EnergyRight_C::Mat_Prog' has a wrong offset!");

}

