#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Common_NewReddot

#include "Basic.hpp"

#include "PyWidget_Common_Reddot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Common_NewReddot.WBP_Common_NewReddot_C
// 0x0010 (0x05E0 - 0x05D0)
class UWBP_Common_NewReddot_C final : public PyWidget_Common_Reddot::UPyWidget_Common_NewReddot
{
public:
	class UMarvelOverlay*                         Overlay_NewReddot;                                 // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_NewReddot;                                    // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Common_NewReddot_C">();
	}
	static class UWBP_Common_NewReddot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Common_NewReddot_C>();
	}
};
static_assert(alignof(UWBP_Common_NewReddot_C) == 0x000008, "Wrong alignment on UWBP_Common_NewReddot_C");
static_assert(sizeof(UWBP_Common_NewReddot_C) == 0x0005E0, "Wrong size on UWBP_Common_NewReddot_C");
static_assert(offsetof(UWBP_Common_NewReddot_C, Overlay_NewReddot) == 0x0005D0, "Member 'UWBP_Common_NewReddot_C::Overlay_NewReddot' has a wrong offset!");
static_assert(offsetof(UWBP_Common_NewReddot_C, Text_NewReddot) == 0x0005D8, "Member 'UWBP_Common_NewReddot_C::Text_NewReddot' has a wrong offset!");

}

