#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Battle_Kill_Panel

#include "Basic.hpp"

#include "PyWidget_LocalBattleKillTest_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Battle_Kill_Panel.WBP_Battle_Kill_Panel_C
// 0x0020 (0x0660 - 0x0640)
class UWBP_Battle_Kill_Panel_C final : public UPyWidget_LocalBattleKillPanel
{
public:
	class UMarvelOverlay*                         Overlay_Content;                                   // 0x0640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_KillPrompt;                                // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_PickUpPrompt;                              // 0x0650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelVerticalBox*                     VBox_Prompt;                                       // 0x0658(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Battle_Kill_Panel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Battle_Kill_Panel_C")
	}
	static class UWBP_Battle_Kill_Panel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Battle_Kill_Panel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Battle_Kill_Panel_C;

}

